### ISSUE TITLE
Test Cases for minimize() method

### ISSUE THREAD

**Issue by julesy89** [msu-coinlab/pymoo#1]
Write test cases that check for random algorithm instances and problems that no exception occurs.

**Comment by lureevnat** [comment]
While running your example code given below, I am getting "No handles with labels found to put in legend." after around 390th iterations. Is there any issue with it?

![image](https://user-images.githubusercontent.com/31588501/52459962-248bc180-2b8e-11e9-8f45-89c7cf378984.png)


`from pymoo.operators.crossover.simulated_binary_crossover import SimulatedBinaryCrossover
from pymoo.operators.mutation.polynomial_mutation import PolynomialMutation
from pymoo.optimize import minimize
from pymoo.util import plotting
from pymoo.util.reference_direction import UniformReferenceDirectionFactory
from pymop.factory import get_problem

problem = get_problem("dtlz1", n_var=7, n_obj=3)
# create the reference directions to be used for the optimization
ref_dirs = UniformReferenceDirectionFactory(3, n_points=91).do()

# create the pareto front for the given reference lines
pf = problem.pareto_front(ref_dirs)

res = minimize(problem,
               method='nsga3',
               method_args={
                   'pop_size': 92,
                   'ref_dirs': ref_dirs},
               termination=('n_gen', 400),
               pf=pf,
               seed=1,
               disp=True)


plotting.plot(res.F)`

**Comment by julesy89** [comment]
Thanks for your comment. The warning is printed after the algorithm run has finished. It has nothing to do with the minimize method, but with plotting.plot. (you can comment it out and verify.)

However, I might like to suppress this warning, because it simply says plt.legend() is called but in this case no legends exist.

Let me know if you find something else of your concern.

**Comment by lureevnat** [comment]
Thank you.
