### ISSUE TITLE
How to recompile libraries

### ISSUE THREAD

**Issue by inaciomdrs** [msu-coinlab/pymoo#10]
I have recently installed pymoo, and when I've the command for verifying if speedup libraries were compiled, the following message appeared:

> Compiled libraries can not be used. Compile for speedup!

How could I recompile (or try to) this libraries manually?

**Comment by julesy89** [comment]
What operating system are you using? Did you use pip to install it?

You can download the last stable version: https://github.com/msu-coinlab/pymoo/archive/0.3.0.zip
Then, extract and try to compile: 

python setup.py build_ext --inplace

Note, that in case you use windows a compiler needs to be installed. I know that for Mac Mojave there might be an issue with a library as well.
 
To install the version if the compilation works just do: 
pip install . 

(make sure you are in the pymoo - not pymoo/pymoo - directory.
