### ISSUE TITLE
pymoo How to add different constants to the Objective Function (OF) in each iteration

### ISSUE THREAD

**Issue by Hericles-Farias** [msu-coinlab/pymoo#100]
Hello, I'm a beginner in Pymoo, my problem is that I want to be able to change the constants of my OF in each time step. How can I do this?

**Comment by julesy89** [comment]
Glad you are intending to use pymoo. Your description of your problem is not sufficient to help you are give you a hint. Can you please provide some more details?

**Comment by Hericles-Farias** [comment]
![1](https://user-images.githubusercontent.com/41486528/94854761-c9ae7a00-0403-11eb-9beb-bbcbd7bdfbd2.PNG)
Hi, thanks for the fast reply. I'm playing with some exercices in order to understand this awesome python library, in the attached file I have two variables (Ein and Eout), all the other parameters are vectors with different values, I wonder if I can solve the system using Pymoo, but I was not able to write the problem like in the Pymoo examples from the website.

**Comment by julesy89** [comment]
Yes, you can use pymoo to solve your problem. The getting started guide covers everything you need to know. Your obective function has a sum, so just use `np.sum` and you are good.
