### ISSUE TITLE
How to add the relative limit for the variable?

### ISSUE THREAD

**Issue by ayubrucelan** [msu-coinlab/pymoo#105]
Hello there!

I'm learning the Pymoo by trying some problem and wondering how to create the variables limits such as below:

0< x1 < 1
0< x2 < 1
0< x3 < x1 - x2

As in every new generation, the value of x3 has to be smaller than x1 -x2.
I hope the explanation is clear enough for you.

Thank you in advance for your kind help!

**Comment by julesy89** [comment]
Just define box constraints (`xl` and `xu`) for all variables to be between 0 and 1.

Then, the third constraint can be considered by:

- Define a constraint `g1` which is: 
x3 < x1 - x2
which is the same as
x3 - x1 + x2 < 0

(see the getting started guide for that: http://pymoo.org/getting_started.html)

-  Or map the third variable to always lie in between 0 and (x1 - x2) by doing: `z3 = x3 * (x1-x2)`
and then using `z3` for the calculation. This makes all solutions being feasible because you have changed the encoding.
(that's only possible for very simply constraint like yours)

**Comment by ayubrucelan** [comment]
Sorry for replying late.

Thank you for your advice, I've successfully deployed the relative limits.

However, I have an additional question about the offsprings.
I'm actually using an external program calculating the functions of every generation and the Pymoo generates _nan_ as some of the random variables from time to time. Is there anything I can do to forbid the Pymoo from generating _nan_ as the variables?

Thank you very much!

**Comment by julesy89** [comment]
I am glad that my suggestions work out for you!

It should not create NaN values. I assume in X space? 
If this should be the case you can provide me code snippet and I can have a look.

**Comment by ayubrucelan** [comment]
Sure, I'm using it as part of my program right now. Please allow me to explain a little about how it works

This code block is called from the main block and the solutions and constraints are calculated by calling the __opt_cal__.
Different from the normal usage, the number of variables, objectives and constraints are various from case to case. However, the amount of variables sent to the __opt_core__ is the same since there are too many of them. In order to keep the fixed variables from changing, I used the same value of xl and xu for them.

For example, 
> If I have variables as x1, x2, x3, x4 and x5
> x4 is fixed to 1 in the current case
> x3 has the relative limit as x3<x1-x2
> others are randomly generated in range 0～1
> 
> then the program gives the limits as
> xl=np.array[0,0,0,1,0]
> xu=np.array[1,1,1,1,1]
> g1=x3 < x1 - x2

In the above example, the X space will generate _nan_ occasionally at the position of x4.

I'm wondering if I force the _nan_ to the previous value in the ___evaluate__ function, will the Pymoo read the renewed X space as the parents or not?

Also, please give me your suggestion and feel free to point out where I did wrong.

The code related to the Pymoo is shown as below:
```
class TestImportProblem(Problem):

    def __init__(self, num_var, xl_in, xu_in, num_obj, num_constr):
        self.n_var = num_var
        self.xl = xl_in
        self.xu = xu_in
        self.n_obj = num_obj
        self.num_constr = num_constr
        self.list_constr = []
        super().__init__(n_var=self.n_var,
                         n_obj=self.n_obj,
                         n_constr=self.num_constr,
                         xl=np.array(self.xl),
                         xu=np.array(self.xu))

    def _evaluate(self, X, out, *args, **kwargs):
        print('X: ')
        print(X)
        list_obj_solution, list_obj_constr = opt_cal.opt_analysis(X)
        out["F"] = np.array(list_obj_solution)
        out["G"] = np.array(list_obj_constr)
        print('out["F"]: ', out["F"])
        print('out["G"]: ', out["G"])


def opt_core(num_gen, num_var, xl_in, xu_in, num_obj, num_constr):
    test_problem = TestImportProblem(num_var, xl_in, xu_in, num_obj, num_constr)
    print('population: ', int(public_var.population))
    res = minimize(test_problem,
                   NSGA2(pop_size=int(public_var.population), eliminate_duplicates=False),
                   ("n_gen", num_gen),
                   save_history=True,
                   verbose=True,
                   seed=1)
    print('variables: \n', res.X)
    res.F = - res.F
    print('solutions:\n', res.F)
    plot = Scatter()
    plot.add(res.F, color="red")
    plot.do()
    plot.show()

```

**Comment by julesy89** [comment]
x4 is not a variable, but a constant. You should not set the lower equal to the upper bound.
you can try to allow 1-eps and 1+eps to have at least a small variation. Or just remove it is a variable. 
Latter shall be prefered.

**Comment by ayubrucelan** [comment]
Thank you for your correction.

Still, I'd like to know if there is any way that allows me to adjust the X space externally?

Because the fixed variable (or constant) is dynamically changing from case to case. Although x4 is a constant in the above case, x1 and x5 might become constant and x4 becomes variable in other cases, for instance.

**Comment by ayubrucelan** [comment]
Or I can revise the X space in between obtain it from the Pymoo and sending it to my calculator( in the _evaluate function). 

If there is any way that allows me to send the revised X space to the Pymoo, please let me know.

**Comment by julesy89** [comment]
You can use a `Repair` operator:
https://pymoo.org/operators/repair.html

**Comment by ayubrucelan** [comment]
Thank you, it fixed my problem perfectly!
