### ISSUE TITLE
some comparisons here FYI

### ISSUE THREAD

**Issue by microprediction** [msu-coinlab/pymoo#107]
https://www.microprediction.com/blog/optimize
https://pypi.org/project/tuneup/

**Comment by julesy89** [comment]
Thanks for letting me know. And nicely done blog post!
I think in the table`PyZoo` should refer to `pymoo`?

What is the purpose of comparing multi- and many-objective algorithms on purely single-objective problems?

I would be curious in rerunning your benchmark. Do you have the defintions of your problems somewhere or can send them to me? 

Julian

**Comment by microprediction** [comment]
Yes PyMoo 😊 thanks
 
Objectives (analytic)
https://github.com/microprediction/tuneup/blob/master/tuneup/ndimsingleobjectives/ndimboxobjectives.py
 
Objectives (likelihood)
https://github.com/microprediction/tuneup/blob/master/tuneup/trivariateobjectives/trivariateboxobjectives.py
 
Comparison scripts:
https://github.com/microprediction/tuneup/tree/master/tuneup/ndimraces

**Comment by microprediction** [comment]
And yes I agree with you re: multi-objective. I think I did make a remark to that effect but I’ll check…
 
We are certainly interested in using multi-objective, which is what attracted me to pymoo to start with.
