### ISSUE TITLE
mix integer programming with constraint

### ISSUE THREAD

**Issue by maamani10** [msu-coinlab/pymoo#109]
![1](https://user-images.githubusercontent.com/61002910/97774761-c0820b80-1b6f-11eb-895a-caf965e418c7.PNG)
hi i saw pymoo and i think its amazing very tnx but i wanna know is it possible to solve a mixed integer programming (mip) in pymoo with pso ? and can u say please how is implementation of these constraints in pymoo? i have more than 20 constraints but with implement these three i can learn its pattern tnx.
T : positive real variable
q(i,j,g) : positive real variable
D(i,j,g) : binary variable
X(i,j,i',j',g): binary variable
A(i,j,g) :  binary variable
W(i,j,g) : positive real variable
S(i,j,g) : integer variable
B  : parameter
M : bigM(parameter) 
i & i' = [1,2,3]
j & j' = [1,2,3]
g = [1,2]

**Comment by julesy89** [comment]
Sorry for my late answer. Have you implemented it yet? 
Equality constraints can be rather challenging to be handled by genetic algorithms and might need a repair operator or a customized algorithm.

**Comment by maamani10** [comment]
hi tnx for answering. no unfortunately i couldnt implement it with pymoo yet.  it will be great if you help me for this. tnx

**Comment by julesy89** [comment]
sorry unfortunatly my time is too limited for such projects. I hope you can figure a way out to implement a genetic algorithm for your problem.
