### ISSUE TITLE
How to write equality constraints?

### ISSUE THREAD

**Issue by aaavendanop** [msu-coinlab/pymoo#111]
Good Morning,

I don't know what is the right way to write equality constraints. I'm new in pymoo and I'll try to understand that.

Thanks.

**Comment by julesy89** [comment]
Equality constraints are challenging to be handled by evolutionary approach in general. 
Using a `Repair` operator is often a more efficient way of handling them.

For more information please have a look at the tutorial here:
https://pymoo.org/misc/constraint_handling.html
