### ISSUE TITLE
Cannot get pareto front of dascmop problems

### ISSUE THREAD

**Issue by patrickphat** [msu-coinlab/pymoo#113]
```python
from pymoo.factory import get_problem, get_visualization
pf = get_problem("dascmop6", 12).pareto_front()
```
in that case `pf = None`

**Comment by patrickphat** [comment]
Quick fix for everyone:
```python
import requests
import os
import numpy as np

basedir = ""
dascmop_pf_urls = [f"https://raw.githubusercontent.com/msu-coinlab/pymoo/master/pymoo/problems/pf/DASCMOP/dascmop{i+1}_1.pf" for i in range(6)]
pareto_fronts = []
for url in dascmop_pf_urls:
    r = requests.get(url, allow_redirects=True)
    raw_name = os.path.basename(url)
    save_name = os.path.join(basedir,raw_name)
    open(save_name, 'wb').write(r.content)
    pareto_fronts.append(np.genfromtxt(save_name))
```

**Comment by patrickphat** [comment]
Quick fix 2: Use dev version
```sh
git clone https://github.com/msu-coinlab/pymoo
cd pymoo
pip install .
```

**Comment by cyrilpic** [comment]
This is actually related to #77.

**Comment by julesy89** [comment]
Thanks for letting me know! I actually thought I have fixed that in the last release, but apparently not.
The issue is the pip package I create to upload on PyPi. As @cyrilpic says correctly during development it works.

**Comment by julesy89** [comment]
I have added the Pareto-front to the latest release. Can you please check if that works for you now?

All the pf files increase the release quite a bit. Probably it would be better to keep an option to download the pf files from a remote server if desired.
