### ISSUE TITLE
When I use NSGA2 and FunctionalProblem to solve problem, the 'type_var=np.int' has no effect

### ISSUE THREAD

**Issue by 2985578957** [msu-coinlab/pymoo#115]
I need to use 'NSGA2(pop_size=pop_size, n_offsprings=n_offsprings, crossover=PointCrossover(n_points=1), mutation=InversionMutation(prob=0.02))' to minimize a FunctionalProblem, and I set 'type_var=np.int' during create the FunctionalProblem, but when it evaluate, the x is still a float array.

**Comment by julesy89** [comment]
The `type_var` does not change the algorithm. `NSGA2` was defined for continuous variables in general. However, you can do some customization by changing the evolutionary operators as shown for a `GA`:
https://pymoo.org/customization/discrete_problem.html
