### ISSUE TITLE
Small issue in nadir_point function

### ISSUE THREAD

**Issue by Kendall-P-Taylor** [msu-coinlab/pymoo#116]
Was just adding some of the problems from the [Real-world Multi-objective Optimization Problem Suite](https://github.com/ryojitanabe/reproblems) to work with pymoo when I found this little error in `problem.py` in the function `nadir_point` line 135: 
`self._ideal_point = np.max(self._pareto_front, axis=0)` 
should read:
`self._nadir_point = np.max(self._pareto_front, axis=0)`
Also, some of the comments refer to 'ideal point' rather than 'nadir point'.

Btw great work on **pymoo**, I'm loving it!

**Comment by julesy89** [comment]
Thank you for letting me know! It will be fixed in the next release.
