### ISSUE TITLE
about MultiObjectiveSpaceToleranceTermination

### ISSUE THREAD

**Issue by wd1969** [msu-coinlab/pymoo#118]
I checked the inside of this function, because the termination process is not smooth in use, because the result of igd is unstable. So I try to improve.

Extract the best 10% from the results of each run and store it in the buffer  buf.shape: (n_gen,  n_gen*0.1, n-obj)

```
[pf, F =  buf[_gen], buf[0:_gen+1]
IGDv = nIGD(pf, F)

def nIGD(pf, F, normalize=False, dist='IGD', **kwargs):
    if normalize:
        nadir_point = pf.reshape(-1,pf.shape[-1]).max(0)
        ideal_point = pf.reshape(-1,pf.shape[-1]).min(0)
    else:
        nadir_point = np.ones( F.shape[-1])
        ideal_point = np.zeros(F.shape[-1])
    rnorm = nadir_point - ideal_point  
    M = pf[:,None,] - F[:,None]; M/= rnorm;  M **= 2; M = np.sqrt(M.sum(-1))
    return M.min(axis=-1).mean(1)

terminate_window = 10
if _gen > terminate_window:
     igdval = (IGDv[-terminate_window:].mean()*_gen)/IGDv.sum()
else:
     igdval = 1
```
Is this output better as a termination condition?

**Comment by julesy89** [comment]
Thank you very much for pointing this out and your code snippet. I am searching for someone who likes to work on termination criterion in general. I have spent some time implementing what is currently in pymoo but haven't found the time to further improve it since then.

Is this from a paper or your own implementation?  What benchmark problems have you checked to see when it terminates?
Can you please make a pull request with an example code I can run to have a look.

**Comment by wd1969** [comment]
I'm sorry I don't know how to add it to pymoo, because I experimented with this feature separately, and the important reason is that I am not familiar with object-oriented programming. This code is out of curiosity. It is difficult for me to understand the uncertain behavior of terminating the benchmark and try to improve it. This function is only the code in the experiment. It needs to use the latest calculation history all igd for each judgment. Of course, this is not What theoretical basis is worse than a whim. I just want to tell you this idea, it would be better if it can help you.

**Comment by julesy89** [comment]
Can you point out what the difference to the current termination is?
I have written a paper about the current implementation: https://www.egr.msu.edu/~kdeb/papers/c2020003.pdf

Does you method need the Pareto front? (that should not be the case, because otherwise it works only for test problems)

**Comment by wd1969** [comment]
The problem with igd for termination is that the best true point is not known in advance. Using the latest Pareto to calculate the adjacent igd is difficult to have an accurate output, so I tried to use the latest Pareto to calculate all the historical igd. And use the latest igd to get the percentage of the cumulative area of ​​the historical igd. The advantage is that the output is smooth enough, because what is obtained is a percentage of the total igd area, so it has nothing to do with the problem.

**Comment by wd1969** [comment]
This function nIGD uses the broadcast mechanism, so it can calculate all historical igd at once without looping, so it does not reduce the speed too much.

**Comment by julesy89** [comment]
Can you elaborate you want to broadcast the calculation?

IGD calculates the distance from a Pareto-optimal point to the closest point in the other (non-dominated) set. The order of points, for example, in NSGA2 is first by rank and then by crowding distance. This means the order from one generation to another will be totally different. Also, we have to use only Pareto-optimal points. They are stored in `opt`; however, their size from one generation to another varies. If you don't calculate the distance between points, how do you calculate IGD?

Or what am I missing?

**Comment by wd1969** [comment]
You may want to get complicated, I just use the latest Pareto best point as a benchmark every time, and recalculate all igd in the history, and you only calculate the previous period (because the Pareto best point is not the global best), So igd is unstable.
Then use the (igd mean * gen) / historical igd sum of the last 10 periods. This output is relatively stable and reliable.

**Comment by julesy89** [comment]
I understood you approach. And the current approach is very simple to be adapted that way. But how do you broadcast? I don't see how this is possible for IGD.

**Comment by wd1969** [comment]
For example:

nobj = 3
n_gen  = 200
pop_size = 200

# (Because the number of Pareto's best points is uncertain each time, it can only be fixed and returned to the front part of the set, such as 10%)
num = pop_size *0.1 

# Create a multidimensional array.
buf = np.full(n_gen, num , nobj)

# Then each cycle:
buf[_gen ]  = np.concatenate(pareto_fronts)[0: num]

# Then you can calculate (all history igd)
pf, F =  buf[gen],  buf[0:_gen+1]
IGDv = nIGD(pf, F)

# Then you can get a stable ratio
terminate_window = 10
if _gen > terminate_window:
     igdval = (IGDv[-terminate_window:].mean()*_gen)/IGDv.sum()
else:
     igdval = 1

**Comment by wd1969** [comment]
# Mainly here, these two arrays are calculated by broadcasting, so as to avoid loops
M = pf[:,None,] - F[:,None]

**Comment by wd1969** [comment]
Sorry, I don’t know how to operate, the font has become too big...

**Comment by julesy89** [comment]
**Please post some code here I can actually run!** (or do a pull request)

I still think the broadcasting solution does not work. The best 10% percent might be nice. However, how do you handle the corner cases? Let us say in generation 5, and we have only one non-dominated solution. In generation 9, we have 13. How would your method handle that? Would the calculation be based on a single solution then? (the 10 percent might not always be possible; that is what I want to say)

**Comment by wd1969** [comment]
I don't quite understand (the 10 percent might not always be possible; that is what I want to say)
Do you mean 10% is not the best level?

**Comment by wd1969** [comment]
We assume that the returned pareto_fronts is a table arranged in the best order, so extracting the first 10% is enough to represent the overall best.

**Comment by julesy89** [comment]
Please post some working code; then, I am sure I understood your idea. We might just not be on the same page about the concept.
You can use the object-oriented interface (https://pymoo.org/getting_started.html#Object-Oriented-Interface), which makes it simpler to determine termination prototypes.

**Comment by wd1969** [comment]
What I mean is that the return size is fixed, it doesn’t matter whether it’s non-dominant, as long as the top 10% represents the overall distance from the best point.

**Comment by wd1969** [comment]
Sorry, I’m late at night here.

**Comment by julesy89** [comment]
Post some working coding example whenever you have developed it.
Julian

**Comment by wd1969** [comment]
Simple implementation is very crude, don't mind.
```
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_problem, get_termination
from pymoo.optimize import minimize
import numpy as np

problem = get_problem("zdt3")
algorithm = NSGA2(pop_size=100)
termination = get_termination("n_eval", 20000)

res = minimize(problem,
               algorithm,
               termination,
               seed=1,
               save_history=True,
               verbose=False)

from pymoo.performance_indicator.igd import IGD
import matplotlib.pyplot as plt

nobj = 2
n_gen = 200
pop_size = 100
num = pop_size//10
buf = np.full((n_gen, num , nobj),np.nan)
terminate_window = 10
terminate_condition = 0.01

def nIGD(pf, F, normalize=False, dist='IGD', **kwargs):
    if normalize:
        nadir_point = pf.reshape(-1,pf.shape[-1]).max(0)
        ideal_point = pf.reshape(-1,pf.shape[-1]).min(0)
    else:
        nadir_point = np.ones( F.shape[-1])
        ideal_point = np.zeros(F.shape[-1])
    rnorm = nadir_point - ideal_point  
    M = pf[:,None,] - F[:,None]; M/= rnorm;  M **= 2; M = np.sqrt(M.sum(-1))
    return M.min(axis=-1).mean(1)

v = []
g = []
for algorithm in res.history:
    _gen = algorithm.evaluator.n_eval//100-1
    
    buf[_gen] = algorithm.pop.get('F')[0:num]
    
    if _gen > terminate_window:
        # 1
        metric = IGD(pf=buf[_gen], normalize=False)
        IGv = metric.calc(buf[_gen-1])
        ##########################################################
        # 2
        pf, F = buf[_gen], buf[0:_gen+1]
        IGDv = nIGD(pf, F)    
        igdval = (IGDv[-terminate_window:].mean()*_gen)/IGDv.sum()
    else:
        igdval = 1
        IGv = 1
        
    v.append(igdval)
    g.append(IGv)
    
    # terminate_condition
    if igdval< terminate_condition: break 
    
    
plt.plot(v, '-o', markersize=4, linewidth=2, color="green")
plt.yscale("log")          # enable log scale if desired
plt.ylabel("IGD")
plt.show()

plt.plot(g, '-o', markersize=4, linewidth=2, color="green")
plt.yscale("log")          # enable log scale if desired
plt.ylabel("IGD")
plt.show()

```

**Comment by wd1969** [comment]
I'm sorry to tell you, this thing is useless. Don't need to be so troublesome to directly use ref_points as pf. The problem is solved
pf = get_reference_directions("das-dennis"。。。。。

**Comment by julesy89** [comment]
reference points and pareto-fronts are something totally different. However, I hope you can get it to work for you example.

**Comment by wd1969** [comment]
```
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_problem, get_termination
from pymoo.optimize import minimize
from pymoo.factory import get_visualization, get_reference_directions
import numpy as np

problem = get_problem("zdt3")
algorithm = NSGA2(pop_size=100)
termination = get_termination("n_eval", 20000)

res = minimize(problem,
               algorithm,
               termination,
               seed=1,
               save_history=True,
               verbose=False)

from pymoo.performance_indicator.igd import IGD
import matplotlib.pyplot as plt

g = []
nobj = 2
n_gen = 200
pop_size = 100
terminate_condition = 0.0025

def nIGD(pf, F, normalize=False, dist='IGD', **kwargs):
    if normalize:
        nadir_point = pf.reshape(-1,pf.shape[-1]).max(0)
        ideal_point = pf.reshape(-1,pf.shape[-1]).min(0)
    else:
        nadir_point = np.ones( F.shape[-1])
        ideal_point = np.zeros(F.shape[-1])
    rnorm = nadir_point - ideal_point  
    M = pf[:,None,] - F[:,None]; M/= rnorm;  M **= 2; M = np.sqrt(M.sum(-1))
    return M.min(axis=-1).mean(1)

ref_dirs = get_reference_directions("das-dennis", 2, n_partitions=12)

for algorithm in res.history:
    
    F = algorithm.pop.get('F')/100   
    
    g.append(nIGD(ref_dirs, -F[None,:]))
    
    if igdval< terminate_condition: break 

plt.plot(g, '-o', markersize=4, linewidth=2, color="green")
plt.yscale("log")          # enable log scale if desired
plt.ylabel("IGD")
plt.show()

```
It's very stable. You can tell by a try
