### ISSUE TITLE
Tuning parameters for DTLZ5(I, M) problem formulation

### ISSUE THREAD

**Issue by roungureanu** [msu-coinlab/pymoo#120]
Hello!

Is there any way to instantiate the **DTLZ5(I, M)** problem, where **I** denotes the dimensionality of the Pareto-optimal surface and **M** is the number of objectives [[link to paper](https://www.iitk.ac.in/kangal/papers/k2005011.pdf)]?

From what I experimented with the framework I see that I can set only the number of variables and the number of objectives of the problem. I think that the framework implements the formulation of the problem referenced in [this](https://tik-old.ee.ethz.ch/file//3ec604450bf683daaf27f9027e69f44d/DTLZ2004a.pdf) article.

Is there any way I can tune these parameters or I should implement a new problem which fits my needs?

**Comment by julesy89** [comment]
I have not implemented the test problem in the paper you are referring to. The DTLZ problem suite is implemented as proposed originally and shown here: https://pymoo.org/problems/many/dtlz.html

However, if you follow the procedure explained in Section 3, this should not be very time-consuming to adapt from the DTLZ5 problem, which already exists. If you are planning to do that, let me know, and I would include the problems for others to use directly in the future.
