### ISSUE TITLE
Polynomial mutation warnings

### ISSUE THREAD

**Issue by vccortez** [msu-coinlab/pymoo#122]
Hi Julian, first of all thank you for your work on Pymoo, it's a great library.

I believe there's a small issue with the `PolynomialMutation` class. Numpy keeps showing this warning:
```
.../pymoo/operators/mutation/polynomial_mutation.py:52: RuntimeWarning: invalid value encountered in power
  d = 1.0 - (np.power(val, mut_pow))
```

I looked into it and it seems like some values of `val` were negative, and `numpy.power` doesn't like negative bases when the exponents are non-integers.

It's only a warning and it doesn't seem to affect the optimization process, but I figured numpy is handling this in some undocumented way and thought it was better to bring it up.

I ended up subclassing and slightly modifying the current polynomial mutation implementation to match the one from [10.1504/IJAISC.2014.059280](https://doi.org/10.1504/IJAISC.2014.059280). If this source also matches your implementation, I could send a PR.

**Comment by julesy89** [comment]
Thanks for reporting. Can you post code here to reproduce the error? Is it possible that you boundaries (`xl` and `xu`) are very close to each other for same variables?

The current implementation matches the one from the C-code of the original NSGA2 implementation (but is implemented vectorized).

**Comment by vccortez** [comment]
I'll try to reproduce it with a script. Boundaries were 0 and 3, it was a discrete variable problem.

**Comment by vccortez** [comment]
Hi @julesy89, the cause of the error was on my code.

Turns out my biased initialization was returning values slightly greater than the upper boundary and that's what made the negative numbers show up on the polynomial mutation implementation. My implementation was slightly different and didn't create negative numbers.

I was surprised though that the `PolynomialMutation`'s attempts to repair the values back into bounds did not seem to work, but I suppose that's my fault to begin with for bringing out-of-bound values.

Sorry for the false alarm.
