### ISSUE TITLE
Should I normalize the objective value before using this package?

### ISSUE THREAD

**Issue by zhenlingcn** [msu-coinlab/pymoo#123]
Recently, I have encountered a black box optimization problem that I don't know the range of objective values in prior. However, from what I know, the scale of objective values is critical for some algorithms, such as MOEA/D. Therefore, should I manually normalize the fitness values, or do this framework have dealt with this problem internally?

**Comment by julesy89** [comment]
Some algorithms handle unnormalized objectives better than others. For instance, MOEA\D uses only the ideal but not the nadir point during decomposition. In contrast to that, NSGA-III uses both. 
If you know the boundaries and can do normalization in your problem formulation itself, it will usually improve the performance of the algorithm. However, if not, the algorithms shall figure out over time appropriate objective space boundaries for your problem.
