### ISSUE TITLE
 Indicator doesn't find ideal cases.

### ISSUE THREAD

**Issue by gyuyoung-hwang** [msu-coinlab/pymoo#124]
Happy New Year.
I am getting a lot of help from the optimization library you uploaded.
Thank you.
I use tensorflow's neural network models as objective functions and constraints to optimize.
However, even if the iteration is repeated, the indicator shows the f value, resulting in an error that can not finally plot the graph. Unlike the example, n_nds also shows only 1 value.
Can I get your help?
this is my cord.

################ Neural Network Model ####################################
import numpy as np
def size(X):
    X2=MinMax_X_size.transform(X)
    Y=size_m.predict(X2)
    Pred_Y = MinMax_Y_size.inverse_transform(Y)
    return Pred_Y

def coverage(X):
    X2=MinMax_X_cov.transform(X) 
    Y=cov_m.predict(X2)
    Pred_Y = MinMax_Y_cov.inverse_transform(Y)
    return Pred_Y

def multi_domain_density(X):
    X2=MinMax_X_DLD.transform(X)   
    Y_pred = DLD_m.predict(X2)
    Y_pred2=np.zeros([Y_pred.shape[0],1])
    for i,s in enumerate(Y_pred):
        if s < 0 : 
            Y_pred2[i] = 0
        else:
            Y_pred2[i] = s
    Y_pred2=MinMax_Y_DLD.inverse_transform(Y_pred2) 
    return Y_pred2

############################################################################
import numpy as np
from pymoo.util.misc import stack
from pymoo.model.problem import Problem

class MyProblem(Problem):

    def __init__(self):
        super().__init__(n_var=4,
                         n_obj=2,
                         n_constr=1,
                         xl=np.array([1010,15,5,0]),
                         xu=np.array([1050,65,20,1.9]),
                         elementwise_evaluation=True)

    def _evaluate(self, x, out, *args, **kwargs):
        print(x,x.shape)
        t=x[0]
        a=x[1]
        g=x[2]
        h=int(x[3])
        con=np.array([t,a,g,h]).reshape(1,4)

        f1 =-size(con)[0] # maximize size 
        f2 = multi_domain_density(con)[0] # minimize density

        g1=45-coverage(con)[0] # get coverage > 45% 
       
        out["F"] = np.column_stack([f1, f2])
        out["G"] = np.column_stack([g1])

elementwise_problem = MyProblem()

**Comment by gyuyoung-hwang** [comment]
Thank you I solved my problem.
~~^^ Happy New year :)!

**Comment by julesy89** [comment]
Great that you were able to solve it. Can you provide some information what the issue was for others who might have the same problem?

**Comment by gyuyoung-hwang** [comment]
Oh.. actually I made some mistake at the step to set my boundary conditions.
 So, I revised them with much reasonable values. I want to help other people as you do!. 
But I just say please check your code again and do practice with great example!
Thank you again Julian.
