### ISSUE TITLE
What is the best way to implement a multitasking multi-objective optimization algorithm in Pymoo?

### ISSUE THREAD

**Issue by zhenlingcn** [msu-coinlab/pymoo#125]
In recent years, multitasking multi-objective optimization has become a hot topic. However, up to now, Pymoo doesn't seem to support this optimization paradigm. I intend to implement this paradigm in Pymoo. Nonetheless, I'm not very familiar with the source code of this project. Therefore, is there any recommended way to do this?

**Comment by julesy89** [comment]
Great that you intend to implement the multitasking approach using pymoo. I think it would be more than great to have one or two state-of-the-art approaches from that more and more popular research field. What algorithm are you trying to implement? Can you post a link to a paper?

Julian

**Comment by zhenlingcn** [comment]
As a matter of fact, the multitasking optimization algorithm is still a novel thing. In general, it is still undetermined which algorithm performs better. Based on my current knowledge, there are some interesting papers that need to be considered.
[1]. The most cited multitask optimization algorithm
[2]. Many-task optimization algorithm (ten tasks simultaneously)
[3]. Machine learning assisted multitask optimization algorithm

[1]. Gupta, Abhishek, Yew-Soon Ong, and Liang Feng. "Multifactorial evolution: toward evolutionary multitasking." IEEE Transactions on Evolutionary Computation 20.3 (2015): 343-357.
[2]. Chen, Yongliang, et al. "An adaptive archive-based evolutionary framework for many-task optimization." IEEE Transactions on Emerging Topics in Computational Intelligence (2019).
[3]. Lin, Jiabin, et al. "Multi-objective Multi-tasking Optimization Based on Incremental Learning." IEEE Transactions on Evolutionary Computation (2019).

**Comment by julesy89** [comment]
Have you been working on multitasking optimization using pymoo recently?
If yes let me know. I think it would be a nice topic to add to the documentation as well if broadly applicable.

**Comment by zhenlingcn** [comment]
Yes, I attempted to use pymoo to implement a simple multitasking optimization algorithm. This function was implemented in my implementation by modifying the traditional evolutionary process into a generator fashion in Python. More specifically, I've limited each NSGA2 instance to run one iteration per call, and then I can exchange data between them. This, I believe, is the most straightforward way to implement this function without significantly altering the source code.

**Comment by zhenlingcn** [comment]
I've written [a blog post](https://zhenlingcn.github.io/2021/03/19/Implementing-multitask-multi-objective-optimization-in-Pymoo.html) to illustrate my point; if you have any thoughts, I'd love to hear them.

**Comment by julesy89** [comment]
Great that you have ended up writing a blog post. Correct me if I am wrong, but isn't the most important aspect of multi-task learning the concept of sharing information to solve each indidividual problem more efficently? How does your source code achieve that? (it looks more or less like independend runs to me).

You can also cite pymoo by (and link our framework to pymoo.org) by the way.

[1] J. Blank and K. Deb, "Pymoo: Multi-Objective Optimization in Python," in IEEE Access, vol. 8, pp. 89497-89509, 2020, doi: 10.1109/ACCESS.2020.2990567.

**Comment by zhenlingcn** [comment]
@julesy89 Hi, Julian, you are right, I'm so sorry that I forgot to answer your question, as I'm not working on multitask MOEA now. In my blog, it provides a way to run several GA tasks simultaneously, and thus it is possible to modify these individuals between the interval of each iteration, thereby achieving multitask MOEA functionality. Because I'm busy now, I regret that I cannot do it furthermore.

**Comment by julesy89** [comment]
No worries. I am glad pymoo is useful for your research!
