### ISSUE TITLE
NSGA2 with mixed variable problem

### ISSUE THREAD

**Issue by pbellino** [msu-coinlab/pymoo#126]
Hi Julian, thank you very much for this great package.

I'm trying to perform a MOO with mixed variable types (floats and integers) using the NSGA2 algorithm.

I get the following error:

```
 =====================================================================================
n_gen |  n_eval |   cv (min)   |   cv (avg)   |  n_nds  |     eps      |  indicator  
=====================================================================================
    1 |     100 | -0.00000E+00 |  6.16317E+01 |       1 |            - |            -
WARNING: Error while preparing the output to be printed.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'float' object has no attribute 'sqrt'
```
I think that for some reason, some variables are not np.float. I've changed the file "pymoo/performance_indicator/distance_indicator.py" to force the np.float:

 ```
  7 def euclidean_distance(a, b, norm=None):
  8     a = a.astype(np.float) # added
  9     b = b.astype(np.float) # added
 10     return np.sqrt((((a - b) / norm) ** 2).sum(axis=1))
```
Now the code runs without error and the solutions seems reasonable. Is it ok my modification? in that case, Is it safe to leave it there or it would affect the performance?

**Comment by julesy89** [comment]
You can fix it even simpler I guess. When you define the problem and set `out["F"]` make sure this is float by `astype.(np.float)`. Can you let me know if this works too?

I was debating if all objectives and constraints should be by default be floats and if not be made one.

**Comment by pbellino** [comment]
You are right,  your solution is simpler and also works. As you said,  in the problem definition I have set:

```
 out["F"] = np.column_stack([f1, f2]).astype(np.float)
 out["G"] = np.column_stack([g1, g2])
```
I've deleted my previous modification to the code.

Thanks!
