### ISSUE TITLE
Issue with DTLZ4

### ISSUE THREAD

**Issue by Kendall-P-Taylor** [msu-coinlab/pymoo#127]
Found a small issue with the implementation of the **DTLZ4** problem in pymoo. The initialisation of the problem in `dtlz.py` line 97 specifies `alpha=100`. This differs from the other problems in the set (which use `alpha=1`), and results in issues when using the `_evaluate()` function on externally generated decision variable vectors. I have changed the value to `1` in my implementation and the problem now performs as expected. Was `alpha=100` set for a specific reason?

**Comment by julesy89** [comment]
Yes. That is how DTLZ4 has been proposed and actually defines the variable density along the front.

Please see the paper: 
"Scalable Test Problems for Evolutionary Multiobjective Optimization" 
On **page 23** the alpha variable is mentioned.

https://tik-old.ee.ethz.ch/file//3ec604450bf683daaf27f9027e69f44d/DTLZ2004a.pdf

**Comment by Kendall-P-Taylor** [comment]
Ah ha! Thanks for the reference, I obviously missed this when I read the paper. Thanks for not just dismissing my post!

**Comment by julesy89** [comment]
You are welcome! And thank you for your patience.
