### ISSUE TITLE
Add support to save plots to file for pymoo.util.running_metric.RunningMetric

### ISSUE THREAD

**Issue by rohitdwivedula** [msu-coinlab/pymoo#130]
Trying to do:

```python3
running = RunningMetric(
    delta_gen=5,
    n_plots = 3,
    only_if_n_plots=True,
    key_press=False,
    do_show=True,
    do_close=True,
)

i = 0
for algorithm in res.history:
    running.notify(algorithm)
    plt.savefig("running_metric_{num}.png".format(num=i));
    i+=1
```

does not work. Just saves a bunch of empty images. The plt.show() is happening inside the notify() function in `visualization/video/callback_video.py`.

**Comment by julesy89** [comment]
First of all, you want to set `do_show ` and `do_close` to `False` if you want to plot or save by yourself after the `notify` call.
Another reason why some of your plots are empty is not the missing capability for saving the figure but the nature of the running metric.

`delta_gen` defines in what generations the metric should be plotted. If you set this to 5, then it will not be plotted in each generation. You can set `delta_gen=1` which would then plot every generation (starting when the `n_plot+1` generation has been reached). 

Also, to force plotting you can call the running metric by 
```
running.notify(algorithm, force_plot=True)
```

which will create a plot every time.

Let me know if this works for you.
