### ISSUE TITLE
User defined algorithm 

### ISSUE THREAD

**Issue by ludohenin** [msu-coinlab/pymoo#132]
I'd like to add OMOPSO but I've actually no idea how to do that (not found in the doc) and if it is even possible.
If it's possible, could you please point how to do that ?

**Comment by julesy89** [comment]
Great! For sure is it possible! I was hoping that some people would like to contribute a few algorithms when I have started the framework. So far, this has barely happened. I recommend looking at existing algorithms, for instance, PSO (https://github.com/msu-coinlab/pymoo/blob/master/pymoo/algorithms/so_pso.py).

Even I still use existing algorithms quite often as a template to implement a new one.

Let me know if you need any more guidance!

**Comment by ludohenin** [comment]
Great, thanks for the (very) fast reply.

I'll let you know if I'm strungling anyhow.
