### ISSUE TITLE
Problem with out of bounds values for SBX in NSGA II

### ISSUE THREAD

**Issue by salijona** [msu-coinlab/pymoo#133]
I am using NSGII for my problem with mixed variables. 
For some integer variables it seems that the  negative values in y1 in SimulatedBinaryCrossover are causing this warning  `RuntimeWarning: invalid value encountered in power
  betaq[mask_not] = np.power((1.0 / (2.0 - rand * alpha)), (1.0 / (self.eta + 1.0)))[mask_not]`

At the same time the algorithm is outputting results out of bounds even when return_least_infeasible=False. I have the lower bounds no less than 0 but  received for some features negative values. 

I tried to look into SimulatedBinaryCrossentropy but still have not found any important insight for this. It seems by default it should take care of the bounds.

**Comment by salijona** [comment]
If someone is experiencing the same issue, after some investigation I found the source of the problem was this line in the function apply_float_operation():  `off = np.rint(off).astype(np.int)` 
Some of my upper bounds  were too large therefore when converting to type np.int they were converted to negative values.  I replaced the line with `off = np.rint(off).astype(np.int64)` to get a larger range and everything works as supposed to now.

**Comment by julesy89** [comment]
Great, that you could figure out the issue. 

Julian

**Comment by thibaultsmnt** [comment]
Hi, 

I'm facing a similar issue.
For a particular gene, I have a lower bound of 0 and an upper bound of 14411015070.
14411015070 overflows the maximum values of an int32.

As pointed out by @salijona, the line `off = np.rint(off).astype(np.int)` is used in the following file https://github.com/msu-coinlab/pymoo/blob/b91212185ab04d006741372a4a480608b8d32e68/pymoo/operators/integer_from_float_operator.py#L24

Depending on the system, the cast to type int will cast to int32 or int64, I suggest updating the line to 
`off = np.rint(off).astype(np.int64)` to have a consistent behaviour and handle large int on all systems.

Should I open a pull request?
