### ISSUE TITLE
Loss of variable-objective synchrony/indexing when using parallelization 

### ISSUE THREAD

**Issue by Nnamdi-Ike** [msu-coinlab/pymoo#136]
It seems like the multithreading process is losing the indexing synchrony between the design space values and the objective space values. As in values result.X[0] is not the solution to result.F[0], it is the solution to result.F[20] if even included in result.F at all. With parallelization off, everything works beautifully. 

Here is the generalized-code

    import numpy as np
    from pymoo.algorithms.nsga2 import NSGA2
    from pymoo.model.problem import Problem
    from pymoo.optimize import minimize
    from multiprocessing.pool import ThreadPool

    class MyProblem(Problem):

    def __init__(self, **kwargs):
        super().__init__(n_var=2,
                         n_obj=3,
                         n_constr=0,
                         xl=np.array([1, 10]),
                         xu=np.array([9, 31]),
                         elementwise_evaluation=True,
                        **kwargs)

    def _evaluate(self, x, out, *args, **kwargs):
        
        MCO_function.n1 = int(x[0])
        MCO_function.n2 = int(x[1])
        MCO_stats = Calculate(MCO_function)
        MCO_stats = MCO_stats.run()
        
    #MCO_stats.array will return integer values. 
        f1 = MCO_stats.array[4] 
        f2 = MCO_stats.array[9]     
        f3 = MCO_stats.array[14] 

        
        out["F"] = [f1, f2, f3]

    n_threads = 16
    
    pool = ThreadPool(n_threads)
    
    problem = MyProblem(parallelization = ('starmap', pool.starmap))
    algorithm = NSGA2(pop_size=120)
    res = minimize(problem,
                   algorithm,
                   ("n_gen", 20),
                   verbose=True,
                   seed=1)
    
    pool.close()

My guess is that it's related to MCO_stats.run(). This function HAS to be run to return the proper MCO_stats.array values. Maybe there is some degeneracy between the threads, saving of solutions and running that function. However, it is my understanding that elementwise evaluation is computing one solution at a time.

**Comment by julesy89** [comment]
If `MCO` is not thread-safe, this will still become an issue. `elementwise_evaluation ` means that the `_evaluate` function retrieves a single solution. However, the built-in features for parallelization will cause this function to be called in parallel (that is the whole purpose of using it).

Does it work without any issues in the regular serialized version?

Also, please make sure the objective values are, in fact, floats and not integers.

**Comment by Nnamdi-Ike** [comment]
Thanks for the quick reply. I can confirm that the values are floats. I cant confirm that the tools I am using are thread safe. My problem is similar to that of this user.
https://github.com/kernc/backtesting.py/issues/125

 The "Calculate" function is really just the `Backtest` class here
https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#gsc.tab=0

defining the `MCO_function` within _evaluate did not work either. 

I was looking to run the example here multithreaded with pymoo.
https://kernc.github.io/backtesting.py/

I was able to get it to work with Jmetal but was interested in trying pymoo to compare speeds.

**Comment by julesy89** [comment]
Does the issue only occur when using thread parallelization? Without any parallelization, it works as expected?
What happens when using processes instead of threads?

If you can post a small example here to reproduce the issue that would be great.
(and interestingly I've had just recently a look at backtesting.py)
