### ISSUE TITLE
how a list help to keep an order for the documentation?

### ISSUE THREAD

**Issue by HeYDwane3** [msu-coinlab/pymoo#139]
Hi, when reading the factory.py, I found the following explaination
`The definitions for each object are purposely defined as a list and not as a dictionary to keep an order for the documentation.`

I am not an experienced Python player, can I ask for more explaination or maybe an example, showing how a list outperformes a dictionary in terms of keeping an order for the documentation?

Thanks

**Comment by julesy89** [comment]
I think you can ignore the comment. I have started to write the `factory.py` a long time ago. The methods can be nice for convenience and can be used to import a lot of classes to create all objects.
