### ISSUE TITLE
Source Code Problem

### ISSUE THREAD

**Issue by TheSilverLinings** [msu-coinlab/pymoo#14]
Hi Julian, I am here seeking you asistance.
There are two problems I met when I read the MOEA/D algorihtm given by pymoo 0.3.0 documentation.

1. 
source code : " ref_dirs = UniformReferenceDirectionFactory(3, n_points=100).do() "
I found it in "from pymop.factory import get_problem, UniformReferenceDirectionFactory"
But when I check the directory of pymop, I didn't find "UniformReferenceDirectionFactory" in factory.py but in util.py. Is there any other method that can link the "UniformReferenceDirectionFactory" ?
2.
I want to change something in your source code to have a better understanding of  code implementation of MOEA/D. I just add some "print()" in, but it didn't work even restarting my computer. Why?
Ubuntu 16.04.
Got the pymoo by pip.
source code I changed is in "/usr/local/lib/python3.5/dist_packages/pymop/util.py" after I modify the file permissions through " sudo chmod 777 * " under the directory of ".../pymop".

To be honest, I am new to both python and the framework.
I hope you would not mind my stupid problems and give me a hand. 
Thanks a lot.

**Comment by TheSilverLinings** [comment]
I has settled the second problem.

**Comment by blankjul** [comment]
Great, happy to hear!

**Comment by TheSilverLinings** [comment]
Okay Julian, Thanks for replying.

**Comment by TheSilverLinings** [comment]
Hi Julian, I am confused with the following source code and my questions is about the python  syntax: 

`class Termination:
    def __init__(self) -> None:
        super().__init__()
        self.flag = True
`
1. I can't find any information in document about `def __init__(self) -> None:`. What does this means?
2. Why Termination can use  `super().__init__()` ?  it is a basic class, isn't it?
It would be better if you can offer guide book to me.
Feel sorry to disturbed you.

**Comment by julesy89** [comment]
1. The `__init__` method is called when the object is generated.

2. Here, this is not necessary indeed. The line could be removed. The IDE I have autogenerated this method with added it automatically. However, not calling the super method might lead to not fully initialized objects in general and can be dangerous.

**Comment by TheSilverLinings** [comment]
Aha, I got it.
But I still don't know why you add ` -> None`   to   `def __init__(self):`. 
I never see a usage like this.

**Comment by TheSilverLinings** [comment]
I got it.
Thank you so much.
