### ISSUE TITLE
CPU intensive computation with NGSA2 ?

### ISSUE THREAD

**Issue by xplsek03** [msu-coinlab/pymoo#140]
Hello, 

great work with pymoo. Very abstract, seems to fulfill my need for solution-space search. I am following this tutorial:
https://pymoo.org/customization/custom.html

I've implemented shifting bottleneck heuristic, which is very CPU intensive, in combination with NSGAII. Is it better to process this computation in overriden _evaluate method of Problem or _do method of Sampling (or is there virtually no difference)?

Thanks.

**Comment by julesy89** [comment]
If it should be executed for every solution it needs to be in `_evaluate`. If you put it in `Sampling` it will only take place for your initial population.

**Comment by xplsek03** [comment]
Thanks.
