### ISSUE TITLE
MOEAD not working for TNK

### ISSUE THREAD

**Issue by dbmptr** [msu-coinlab/pymoo#141]
I tried the following code:
```
problem = get_problem("tnk")
algorithm = MOEAD(
    get_reference_directions("das-dennis", 2, n_partitions=10),
    n_neighbors=15,
    decomposition="pbi",
    prob_neighbor_mating=0.8,
    seed=1
)
res = minimize(problem, algorithm, termination=('n_gen', 200))
```
But then the `res.F` is None.
I am using  pymoo-0.4.2.2

**Comment by julesy89** [comment]
MOEA\D does not support any constraints, but NSGA-III does. Maybe I should add a warning when someone just attempts to use MOEA\D for constrained problems.
I know that some researchers have worked on extending it to consider constraints. If you plan on adding it to the code please let me know and I can add it to the stable release.
