### ISSUE TITLE
Defining external evaluation

### ISSUE THREAD

**Issue by TheFaither** [msu-coinlab/pymoo#142]
Hi,
I was recently asked to implement a multi-objective optimization in my code, and I was interested in using pymoo since I've already read the docs and run some examples and it looks great. However, it is not clear to me if I can apply it to my work, where the evaluation is made by an external script and all the data concerning a single simulation is printed in an hdf file. Intuitively "print x in file A, evaluate, read f in file A" seems an easy task and it shouldn't be different from calling other numpy functions, but I strongly feel I may be wrong here.

Edit: After some additional studies of the examples, I think this could suffice, but I'm still afraid I may be missing something
`     

    def _evaluate(self, X, out, *args, **kwargs):
        # Print the matrix x to the external file
        external_evaluator.__printtoh5__("simulation.h5",X,"x")
        # Evaluate the external problem and wait for it to finish
        external_evaluator.__evaluateh5__()
         # Get the list of results to be minimized [f1,f2,f3,...]
       out["F"] = np.column_stack(external_evaluator.__getfromh5__("simulation.h5","f"))
`

Thank you in advance,
Daniele

**Comment by julesy89** [comment]
Looks good to me. Make sure all objectives are supposed to be minimized or otherwise multiply the one which is supposed to be maximized by -1. Also, ensure that the objectives are float variables.

For pymoo it does not really matter if the function values come from an equation or an external function.
