### ISSUE TITLE
Pymoo for hyperparameter tuning

### ISSUE THREAD

**Issue by balajimohan87** [msu-coinlab/pymoo#145]
Hi, I would like to use Pymoo for hyperparameter tuning for machine learning algorithms. I want to get help in selecting, mutating, and crossover from the dictionary of categorical string variables. For example, the kernel hyperparameter of the SVR model can take only values from ["poly", "rbf", "sigmoid"]. I read through the customization section from the website but still do not understand how this could be done with Pymoo.
Your help is much appreciated.

**Comment by julesy89** [comment]
You can define a mixed-integer optimization problem as shown here: 
https://pymoo.org/customization/mixed_variable_problem.html

You map the integer to the kernel, e.g. 0 -> poly, 1-> rbf, and so on. This assumes, however, that all the other variables do not heavily depend on the kernel choice. It might be better to do independent runs for each kernel.
