### ISSUE TITLE
*args and **kwargs in the evaluate signature

### ISSUE THREAD

**Issue by iurisegtovich** [msu-coinlab/pymoo#146]
hi,
I saw that when defining a problem < https://pymoo.org/problems/index.html >
we can have *args and **kwargs in the _evaluate_ signature.

however i was unable to pass some args later,
minimize did not take my args,
i did not find a problem.set_args method or similar

i guess i could save some args as myproblem.args and use them in evaluate as self.args as a workaround

but i was expecting to be able to pass those args as arguments to some established methods and see them arrive in the evaluate arguments

am i missing something here?

this is a gist with some of the code from getting started copied and comments where i hoped args would work  https://colab.research.google.com/gist/iurisegtovich/f774932dcf4ebf5e6b09b4b823dd8ec6/pymoo_args.ipynb >

**Comment by julesy89** [comment]
What about adding the `args` in the constructor of the `Problem` object?

```
class MyProblem(Problem):


    def __init__(self, args):

        # define lower and upper bounds -  1d array with length equal to number of variable
        xl = -5 * anp.ones(10)
        xu = 5 * anp.ones(10)

        super().__init__(n_var=10, n_obj=1, n_constr=2, xl=xl, xu=xu, evaluation_of="auto")

        self.args = args

        

    def _evaluate(self, x, out, *args, **kwargs):
        f = anp.sum(anp.power(x, 2) - self.const_1 * anp.cos(2 * anp.pi * x), axis=1)
        g1 = (x[:, 0] + x[:, 1]) - self.const_2
        g2 = self.const_2 - (x[:, 2] + x[:, 3])

        print(self.args) 

        out["F"] = f
        out["G"] = anp.column_stack([g1, g2])
```


Your arguments will probably be constants anyway and will not change for the run with that problem.
Please let me know if this works for you.

**Comment by iurisegtovich** [comment]
This solution works, it does get the objects wrapped as args, from somewhere else of my program, into the evaluate method where I need to use them.
This is a perfect oop solution, I guess, saving my args as a self.args property,
in the same way as self.const_1 and self.const_2 in the example.

However, when I saw the *args dummy in the _evaluate signatures, I was under the impression that they would work like scipy routines (optmize.root, optimize.minimize, integrate.odeint, etc...)
```
#https://docs.scipy.org/doc/scipy-0.15.1/reference/tutorial/optimize.html
res = minimize(func, [-1.0,1.0],           args=(-1.0,),           jac=func_deriv,
...                method='SLSQP', options={'disp': True})
#the method will call func( xi, *args) for each trial xi
```

So I wondering if there is a "functional" way of passing the args via the *args dummy argument of _evaluate,
or otherwise, what is the purpose of that dummy, maybe it colud be defined as 

`def _evaluate(self, x, out, ):`

without *args or **kwargs

but then, it looks like the dummy **kwargs in _evaluate is getting an algorithm instance, even though unused there.

**Comment by julesy89** [comment]
There is not a functional way because in contrast to SciPy the problem can be defined using an object. This way, there is no necessity of passing additional arguments to the problem during evaluation because they can be store in the object directly.

However, if you have a use case that is not covered this way please let me know.

**Comment by iurisegtovich** [comment]
i don't have a use case not covered.
i think the usage is fine with the oop approach.
thanks for your replies

**Comment by SimonPeople** [comment]
I have a use case. I want to pass an object to __evaluate_ that is not picklable. So adding it to the constructor is no option because the _deepcopy_ function won't work.

**Comment by julesy89** [comment]
you can exclude attributes from being pickles if this is what you want:
`self.exclude_from_serialization = self.exclude_from_serialization + ["runner"]` where `runner` is the attribute here.

Or overwrite the state method by yourself:
```
    def __getstate__(self):
        if self.exclude_from_serialization is not None:
            state = self.__dict__.copy()
            # exclude objects which should not be stored
            for key in self.exclude_from_serialization:
                state[key] = None
            return state
        else:
            return self.__dict__
```
