### ISSUE TITLE
Explanation of displayed results when verbose is True

### ISSUE THREAD

**Issue by jungla88** [msu-coinlab/pymoo#149]
Hello,

I'm using pymoo for multi objective optimization using NSGA-2.
I found a bit hard finding references for the display output when minimize function is initialize with verbose = True.
This is my current output:

`n_gen |  n_eval |  n_nds  |     eps      |  indicator  
` 

The first three columns are quite intuitive (even if i am assuming n_nds are number of non dominated individuals), but i am totally confused about eps and indicator. Additionally, indicator outputs some strings which i cannot understand: ideal, nadir, f.
I would like an explanation or some references for better understanding the evolution.

Thank you and great job!

**Comment by julesy89** [comment]
The next release will have updated documentation where the columns are explained.

[![expl.png](https://i.postimg.cc/vBTvWyjX/expl.png)](https://postimg.cc/LYdfpcmZ)

For eps/indicator I would like to refer to:
https://www.egr.msu.edu/~kdeb/papers/c2020003.pdf
