### ISSUE TITLE
Allowing continuous and discrete variable on AWS batch

### ISSUE THREAD

**Issue by phylroy** [msu-coinlab/pymoo#15]
Hi there,

Great package! I was wondering how to optimize with continuous as well as discrete(integer) variables  at the same time. Is this possible?

Also, to evaluate my function.. the problem _evaluate is rather processor intense...would I be able to send the work to something like [AWS batch](https://aws.amazon.com/batch/) to run the def _evaluate portion of the problem to speed up the solution?

Thanks!

Phylroy

**Comment by julesy89** [comment]
Currently, mixed variable optimization is not supported out of the box. However, it can be manually incorporated by writing custom operators (sampling, crossover, mutation). 

I am working on the new release right now, which I will release in the end of this month most likely, and there mixed variables will be included. Also, a tutorial will be provided on the homepage. The implementation is based on defining operators, for instance a crossover, with a mask which defines the variable types and the corresponding crossover implementation for each variable type in a dictionary.

The _evaluate function takes a list of individuals. In the end, the dictionary _out_ is filled with the evaluated values. In between you can use any possible speedup. For example, if you choose a population size of 100 then you can easily distribute those 100 evaluations on a cluster and then, finally, when the solutions are evaluated store the results in out["F"] and out["G"] (if constraints are present). This is one advantage of population-based optimization that parallelization can be implemented without modifying the algorithm itself.

**Comment by wzbernstein** [comment]
Hi there!  We, too, would like to use pymoo for a continuous+discrete variable search.  We will be looking forward to the next release.  Thanks for your hard work.
-Bill

**Comment by julesy89** [comment]
I have released the new pymoo version 0.3.1.
A small example: https://pymoo.org/tutorial/mixed_variable_problem.html

Please let me know if this covers all you need.
- Julian

**Comment by rtn92** [comment]
Looks gorgeous. Thank you very much, Julian, I appreciate it!
