### ISSUE TITLE
Problem of IGD

### ISSUE THREAD

**Issue by Wang-XR** [msu-coinlab/pymoo#153]
Hi，I want to know if I can adjust the parameter P in the formula IGD, such as p=1. Looking forward to your reply.

**Comment by julesy89** [comment]
You can implement your own performance indicator. Feel free to look at my IGD implementation:

```
import numpy as np
from pymoo.performance_indicator.distance_indicator import DistanceIndicator, euclidean_distance


def euclidean_distance(a, b, norm=None):
    return np.sqrt((((a - b) / norm) ** 2).sum(axis=1))


class IGD(DistanceIndicator):

    def __init__(self, pf, **kwargs):
        super().__init__(pf, euclidean_distance, 1, **kwargs)

**Comment by Wang-XR** [comment]
Thank you very much for your answer. I found that your code is a little different from the formula of IGD, and I don't know why (it may be because of my misunderstanding).I would appreciate it if you could answer my question.
![IGD](https://user-images.githubusercontent.com/82993367/116281985-d7bb5200-a7bc-11eb-8e7a-6cf0cecf32b6.jpg)

**Comment by julesy89** [comment]
I recommend having a look at "Modified Distance Calculation in Generational Distance and Inverted Generational Distance". 
You will find some example calculations there. I have written test cases for the performance indicators (IGD, IGD+, GD, GD+) to match the numbers from the paper.

Please let me know if this resolves the issue.

**Comment by Wang-XR** [comment]
Thanks for your answer, I am sorry that there are some errors in the pictures given. I have read this article, the author the author set p=1 and pointed out some shortcomings of IGD and GD, and proposed IGD+ and GD+. Here is the comparison of your code and formula (IGD),where p=2.
import numpy as np
def euclidean_distance(a, b, norm=2):
    return np.sqrt((((a - b) / norm) ** 2).sum(axis=1))
def vectorized_cdist(A, B, func_dist=euclidean_distance, fill_diag_with_inf=False, **kwargs):
    u = np.repeat(A, B.shape[0], axis=0)
    v = np.tile(B, (A.shape[0], 1))

    D = func_dist(u, v, **kwargs)
    M = np.reshape(D, (A.shape[0], B.shape[0]))

    if fill_diag_with_inf:
        np.fill_diagonal(M, np.inf)

    return M
#obtained PF
A=np.array([[2,2],[3,3]])
#true pareto front
B=np.array([[0,0],[1,1]])
M=vectorized_cdist(A, B, func_dist=euclidean_distance, fill_diag_with_inf=False)
M
#IGD calculated by your code
M1=np.mean(np.min(M, axis=1))
print(M1)
#In fact, it is the following result
((np.sqrt(8)+np.sqrt(2))/2)/2
#IGD calculated by formula
M2=np.sqrt((np.sqrt((2-0)**2+(2-0)**2))**2+(np.sqrt((2-1)**2+(2-1)**2))**2)/2
print(M2)
#In fact, it is the following result
np.sqrt(10)/2

**Comment by Wang-XR** [comment]
Thanks for your answer, I am sorry that there are some errors in the pictures given. I have read this article,  the author set p=1 and pointed out some shortcomings of IGD and GD, and proposed IGD+ and GD+. Here is the comparison of your code and formula (IGD),where p=2.
import numpy as np
def euclidean_distance(a, b, norm=2):
return np.sqrt((((a - b) / norm) ** 2).sum(axis=1))
def vectorized_cdist(A, B, func_dist=euclidean_distance, fill_diag_with_inf=False, **kwargs):
u = np.repeat(A, B.shape[0], axis=0)
v = np.tile(B, (A.shape[0], 1))

D = func_dist(u, v, **kwargs)
M = np.reshape(D, (A.shape[0], B.shape[0]))

if fill_diag_with_inf:
    np.fill_diagonal(M, np.inf)

return M
#obtained PF
A=np.array([[2,2],[3,3]])
#true pareto front
B=np.array([[0,0],[1,1]])
M=vectorized_cdist(A, B, func_dist=euclidean_distance, fill_diag_with_inf=False)
M
#IGD calculated by your code
M1=np.mean(np.min(M, axis=1))
print(M1)
#In fact, it is the following result
((np.sqrt(8)+np.sqrt(2))/2)/2
#IGD calculated by formula
M2=np.sqrt((np.sqrt((2-0)**2+(2-0)**2))**2+(np.sqrt((2-1)**2+(2-1)**2))**2)/2
print(M2)
#In fact, it is the following result
np.sqrt(10)/2

**Comment by Wang-XR** [comment]
Thanks for your answer, I am sorry that there are some errors in the pictures given. I have read this article, the author set p=1 and pointed out some shortcomings of IGD and GD, and proposed IGD+ and GD+. Here is the comparison of your code and formula (IGD),where p=2.

`import` numpy as np
`def` euclidean_distance(a, b, norm=2):
return np.sqrt((((a - b) / norm) ** 2).sum(axis=1))

`def` vectorized_cdist(A, B, func_dist=euclidean_distance, fill_diag_with_inf=False, **kwargs):
u= np.repeat(A, B.shape[0], axis=0)
v= np.tile(B, (A.shape[0], 1))
D= func_dist(u, v, **kwargs)
M= np.reshape(D, (A.shape[0], B.shape[0]))
if fill_diag_with_inf:
np.fill_diagonal(M,np.inf)
return M
#obtained PF
A=np.array([[2,2],[3,3]])
#true pareto front
B=np.array([[0,0],[1,1]])
M=vectorized_cdist(A,B, func_dist=euclidean_distance, fill_diag_with_inf=False)
M
#IGD calculated by your code
M1=np.mean(np.min(M,axis=1))
print(M1)
#In fact, it is the following result
((np.sqrt(8)+np.sqrt(2))/2)/2
#IGD calculated by formula
M2=np.sqrt((np.sqrt((2-0)**2+(2-0)**2))**2+(np.sqrt((2-1)**2+(2-1)**2))**2)/2
print(M2)
#In fact, it is the following result
np.sqrt(10)/2

**Comment by julesy89** [comment]
I am not really sure what your last answer should tell me. 

First of all, your Pareto-front `B` does not make any sense. Because (0,0) clearly dominates (1,1). By any means that can not be a valid Pareto front. The same holds for `A` which in fact could be the results, but you will have to extract the non-dominated solutions out of it that the IGD calculation makes sense.

Second, please see the script below which is the IGD calculation as a script that matches the results from the `IGD` class in Python. I have changed the point sets to be non-dominated. 

Please let me know if this matches now your hand calculations.

```
import numpy as np
from pymoo.performance_indicator.igd import IGD
from pymoo.util.misc import vectorized_cdist


def euclidean_distance(a, b):
    return np.sqrt(((a - b) ** 2).sum(axis=1))


# obtained results
F = np.array([[2.0, 0.0], [1.0, 1.0], [0.0, 2.0]])

# true pareto front
pf = np.array([[0.0, 0.1], [0.1, 0.0]])

# calculate distance from each point in pareto front to each point in F
D = vectorized_cdist(pf, F, func_dist=euclidean_distance)

# find the closest point for each solution in the pareto front
closest = D.min(axis=1)

# IGD calculated manually
igd = np.mean(closest)

print("Manual:", igd)

print("Implementation:", IGD(pf).calc(F))

```

**Comment by Wang-XR** [comment]
Thank you very much for your patient answers, and sorry that I forgot to consider the non-dominant situation. I think your code is completely correct in the case of p=1. The following is the code I think in the case of p=2, because I saw on the webpage (https://pymoo.org/) that the formula you gave is the case of p=2 (by the way, I want to ask, in euclidean_distance ，what variable does the norm represent)
F = np.array([[2.0, 0.0], [1.0, 1.0], [0.0, 2.0]])
pf = np.array([[0.0, 0.1], [0.1, 0.0]])
u = np.repeat(pf, F.shape[0], axis=0)
v = np.tile(F, (pf.shape[0], 1))
D=(np.sqrt(((u-v)**2).sum(axis=1)))**2
M = np.reshape(D, (pf.shape[0], F.shape[0]))
closest=M.min(axis=1)
igd=np.sqrt(sum((closest)))/2
print(igd)
Thanks again for your patient guidance！

**Comment by julesy89** [comment]
for changing p, just replace the `euclidean_distance` by the pnorm. 
the current implementation uses p=2 (which is the same as Euclidean Distance)

`norm`: if the objectives have different scales, this needs to be considered by normalization each of them (using ideal and nadir point)

**Comment by Wang-XR** [comment]
Thank you for your answer. I would like to ask if my calculation result is correct when p=2?

**Comment by julesy89** [comment]
I am not sure how to say it in other words. My code above is the correct implementation for p=2. And the results do not match yours. To make your code match:

```
u = np.repeat(pf, F.shape[0], axis=0)
v = np.tile(F, (pf.shape[0], 1))

p = 2
D = ((u - v) ** p).sum(axis=1) ** (1/p)

M = np.reshape(D, (pf.shape[0], F.shape[0]))
closest = M.min(axis=1)
igd = closest.mean()
print("Step-Wise:", igd)

```

**Comment by julesy89** [comment]
Okay, I just had another look. What are you planning to change? The distance measure itself or the IGD measure directly?
We might have talked about different things here.

**Comment by Wang-XR** [comment]
I want to confirm whether my understanding of the formula IGD is correct and I may know where we understand it differently.
![1Q(5XRF@_NM6 W @I5%{QNN](https://user-images.githubusercontent.com/82993367/116963445-7246f400-acdb-11eb-9ced-fae5158a8afa.png)
I think the "d" in this paper stands for Euclidean distance (After calculating the Euclidean distance, calculate the power of p, then add the sum, and finally calculate the power of 1/p). And your understanding does not seem to be.You seem to understand it as Minkowski distance(Euclidean distance is a special case of it), but it is not exactly the same, because Minkowski distance needs to be calculated by absolute value

**Comment by julesy89** [comment]
Okay, sorry now I understand what you are trying to achieve. I had the impression you want to change the norm (that is basically what IGD+ does).

Having said that, then the IGD implementation in pymoo (as you said) is based on `p=1` which is most commonly calculated.

What is your concrete question now? Is it not then simply the code below?

```
u = np.repeat(pf, F.shape[0], axis=0)
v = np.tile(F, (pf.shape[0], 1))

D = ((u - v) ** 2).sum(axis=1) ** 0.5

M = np.reshape(D, (pf.shape[0], F.shape[0]))

closest = M.min(axis=1)

p = 1
igd = ((closest ** p).sum() ** (1 / p)) / len(closest)
print(f"With p={p}:", igd)
```

**Comment by Wang-XR** [comment]
Because I have seen some articles using IGD in the case of p=2 (such as MOGWO, Multi-Objective-Grey-Wolf-Optimization), and then I found your code and the formula in the article (Modified Distance Calculation in Generational Distance and Inverted Generational Distance) are a bit different, I don’t know why they are different, so I’m asking you. This is my question, maybe my expression is not clear, sorry for that.
This code should be the formula I understand (is my understanding correct?)
Your code is very well written. Thank you for your patience and guidance. I wish you all the best in your research.
