### ISSUE TITLE
Pareto front of WFG1-3 missing

### ISSUE THREAD

**Issue by VeritasXu** [msu-coinlab/pymoo#157]
Many thanks for the open source and maintenance of pymoo.

There exists a tiny bug in WFG 1-3 problem:

Once using WFG1-3 as the test problem, the problem.pareto_front() method will return None instead of real pf. 

After checking the source code, I found that the class method _calc_pareto_front(self, ref_dirs) of WFG1-3 is missing.

Could you please tell me how to fix it? thanks.

**Comment by julesy89** [comment]
It is not really a bug but I have not found the time yet to implement the PFs. Because of the density of the Pareto-front in the search space, it is not that trivial to create the PFs.
Either you implement the corresponding `_calc_pareto_front` by yourself (let me know if you do so) or you use another performance indicator like HV. (note that this can become computationally expensive for larger dimensions)

**Comment by VeritasXu** [comment]
Thank you, I will implement it later and will post it at the end of this issue.

**Comment by VeritasXu** [comment]
@

> It is not really a bug but I have not found the time yet to implement the PFs. Because of the density of the Pareto-front in the search space, it is not that trivial to create the PFs.
> Either you implement the corresponding `_calc_pareto_front` by yourself (let me know if you do so) or you use another performance indicator like HV. (note that this can become computationally expensive for larger dimensions)

Hi, I implement the _calc_pareto_front() function for WFG 1-3 (3 objectives) in "Lib\site-packages\pymoo\problems\many\wfg.py" according to the implementation of platEMO.

For WFG1:

    def _calc_pareto_front(self):
        if self.n_obj ==3:
            a = np.linspace(0, np.pi/2, 10).reshape(-1, 1)
            x = (1 - np.cos(a)) * (1 - np.cos(a.T))
            y = (1 - np.cos(a)) * (1 - np.sin(a.T))
            z = 1 - a * np.ones(a.T.shape) * 2 / np.pi - \
                np.cos(20 * a * np.ones(a.T.shape) + np.pi / 2) / 10 / np.pi
            return np.hstack((2 * x.reshape(-1, 1), 4 * y.reshape(-1, 1), 6 * z.reshape(-1, 1)))
        else:
            return None

For WFG2:
firstly should import non dominated sorting:

from pymoo.util.nds.non_dominated_sorting import NonDominatedSorting

    def _calc_pareto_front(self):
        if self.n_obj ==3:
            a = np.linspace(0, np.pi/2, 40).reshape(-1, 1)
            x = ((1 - np.cos(a)) * (1 - np.cos(a.T))).reshape(-1, 1)
            y = ((1 - np.cos(a)) * (1 - np.sin(a.T))).reshape(-1, 1)
            z = (1 - a * np.ones(a.T.shape) * 2 / np.pi * \
                np.power(np.cos(10 * a * np.ones(a.T.shape)), 2)).reshape(-1, 1)
            pf = np.hstack((x, y, z))
            nds = NonDominatedSorting()
            fronts = nds.do(pf)
            data_index = list(fronts[1])
            for i in range(2, len(fronts)):
                data_index += list(fronts[i])
            z[data_index] = np.nan

            return np.hstack((2 * x, 4 * y, 6 * z))
        else:
            return None

For WFG3:

    def _calc_pareto_front(self, num=1000):
        if self.n_obj < 4:
            x = np.linspace(0, 1, num).reshape(-1, 1)
            x = np.hstack((x, np.zeros((num, self.n_obj - 2)) + 0.5, np.zeros((num, 1))))
            R = np.fliplr(np.cumprod(np.hstack((np.ones((num, 1)), x[:, 0:2])), 1)) * \
                np.hstack((np.ones((num, 1)), 1 - x[:, ::-1][:,1:3]))
            R = np.tile(np.arange(2, 2 * (self.n_obj + 1), 2), (num, 1)) * R

            return R
        else:
            return None
 
please note that the pareto front of WFG3 cannot be plotted by your plot funtion with error: "Error in qhull Delaunay triangulation calculation: singular input data (exitcode=2);", but can be plotted directly use plt.scatter(pf[:, 0], pf[:, 1], pf[:,2] ,c="r").

Please check if it is correct. Hope for a new version.

**Comment by VeritasXu** [comment]
Thank you! I will compare these two implementations, and will futher consult the authors and try to implement it with python more accurately in a few days when I am free.
