### ISSUE TITLE
Result not showing objective and design variable values

### ISSUE THREAD

**Issue by NumairManhas** [msu-coinlab/pymoo#158]
Hi , I am using Pymoo for the first time , i am evaluating the standard problem given in pymoo website , i am not getting optimum functional values and corresponding design values 
Please see below :

import numpy as np
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.model.problem import Problem
from pymoo.optimize import minimize

class MyProblem(Problem):

    def __init__(self):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=2,
                         xl=np.array([-2,-2]),
                         xu=np.array([2,2]),
                         elementwise_evaluation=True)

    def _evaluate (self, X, out, *args, **kwargs):
        f1 = X[0] ** 2 + X[1] ** 2
        f2 = (X[0]-1) ** 2 + X[1] ** 2

        g1 =  2 * (X[0] - 0.1) * (X[0] - 0.9) / 0.18
        g2 = - 20 * (X[0] - 0.4) * (X[0] - 0.6) / 4.8

        out["F"] = [f1, f2]
        out["G"] = [g1, g2]
        
problem = MyProblem()

algorithm = NSGA2(pop_size=10)

res = minimize(problem,
               algorithm,
               ("n_gen", 10),
               verbose = True,    
               seed = 1)

The result that i am getting only includes those things 
n_gen |  n_eval |   cv (min)   |   cv (avg)   |  n_nds  |     eps      |  indicator 

I want to get function values and design variables .
Thank you

**Comment by julesy89** [comment]
The values you are interested in are stored in the `Result` objective.
Please have a look at our documentation here:
https://pymoo.org/interface/result.html

**Comment by NumairManhas** [comment]
Thanks will check it out
