### ISSUE TITLE
Multi-Objective Optimization

### ISSUE THREAD

**Issue by rabiu42000** [msu-coinlab/pymoo#159]
If I use pymoo Decomposition techniques such as ASF or AASF will the result return a set of non-dominated solutions?
How do read results (decision variables and objectives) for the set of non-dominated solutions?

**Comment by julesy89** [comment]
Yes, it will. For basic questions about multi-objective optimization, I encourage you to have a look at the literature. For instance:
`Multi-Objective Optimization using Evolutionary Algorithms` by `Kalyanmoy Deb`.

Results are in the `res` objective as shown in the tutorials. `res.X` gives you the decision variables and `res.F` the objectives.
Please have a look at https://pymoo.org/interface/result.html for more information.

**Comment by rabiu42000** [comment]
Thank you very much. Your information was so helpful.
