### ISSUE TITLE
About constraint value

### ISSUE THREAD

**Issue by Guinsoon** [msu-coinlab/pymoo#16]
In https://pymoo.org/getting_started.html, the code set constraint "𝑔1(𝑥)=𝑥21−𝑥1≥−3/16" to "𝑔1(𝑥)=−(𝑥21−𝑥1+3/16)≤0", which g(x) < 0.
However, in https://www.egr.msu.edu/coinlab/blankjul/pymop/#zdt, Custom Problem section, the code set "x1 + x2 > var2" to "(x[:, 0] + x[:, 1]) - self.const_2", which g(x) > 0.
Which one is correct?

**Comment by julesy89** [comment]
The pymoo documentation is correct. Constraints are always <= constraints. 
Thanks for pointing out the descriptions are deviating.

The problem framework pymop will be outdated soon, because I have already merged it into pymoo.

**Comment by Guinsoon** [comment]
> The pymoo documentation is correct. Constraints are always <= constraints.
> Thanks for pointing out the descriptions are deviating.
> 
> The problem framework pymop will be outdated soon, because I have already merged it into pymoo.
Thanks for your reply

**Comment by Guinsoon** [comment]
Thanks for your reply.
