### ISSUE TITLE
What does plot.do() do?

### ISSUE THREAD

**Issue by Justin1904** [msu-coinlab/pymoo#160]
Thanks for the amazing library and tutorials! I found that in some of the visualization examples, a `plot.do()` method is called for some examples but not for others (e.g. [this example](https://pymoo.org/getting_started.html#Results) contains two plots, one with `.do()` one without). Could you explain a bit about what does this method do? I didn't seem to find the documentation for it.

**Comment by julesy89** [comment]
`plot.do()` creates the plot in the current figure of matplotlib, but does not show it (that is what `plot.show()` includes. it executes `.do()` and shows it.
`plot.do()` can become handy if you like to manipulate the plot further using matplotlib commands before showing it.
