### ISSUE TITLE
Feature query - customizing standard implementation 

### ISSUE THREAD

**Issue by preritt** [msu-coinlab/pymoo#162]
Hi
I was looking customize implementation of a standard genetic algorithm.  I would like to inject some individuals using a modified procedure besides crossover and mutation in genetic algorithm (I would like to retain some but not all individuals using crossover and mutation). 
Is there a way to do so, and can you please tell me where should the changes be made?

Is callback the right place?
https://www.pymoo.org/interface/callback.html

Thanks

**Comment by julesy89** [comment]
It will be more of a hack, but you can either use the `Callback` or the `Repair` operator. 
Another way is not running the minimize method but coding the loop and calling `algorithm.next()` until the algorithm terminates. (see the object-oriented interface in the https://pymoo.org/getting_started.html).

You can inject a solution by replacing an individual in `pop` or by appending a whole sub-population by `Population.merge(pop, others)`.

(and sorry for the delayed answer)

**Comment by preritt** [comment]
No problem, thanks for the response! 
I will try this and see how it goes.
