### ISSUE TITLE
Meaning of string "f" in results display and behavior of "Indicator output"

### ISSUE THREAD

**Issue by Joslusuca** [msu-coinlab/pymoo#164]
Hello!... Thanks a lot for Pymoo.
I was able to infer the meaning of "nadir" and "ideal" from the reference (https://www.egr.msu.edu/~kdeb/papers/c2020003.pdf). However, I still do not understand the meaning of "f". Does it mean there are no changes for the ideal or nadir points? Or does it mean that generation Fails?
If this string (indicator output) changes when the ideal (or nadir) point is updated, what happens if they both (nadir and ideal point) change in the same generation?
Again, thanks so much for this amazing contribution!

**Comment by julesy89** [comment]
The meaning of `f` is the overall movement of the non-dominated solutions normalized by `ideal` and `nadir`. If you are familiar with IGD, you can think of the current generation being your Pareto front Approximation and the last generation of your obtained result set. 

The termination is based on if `ideal`, `nadir`, or `f` have not changed significantly for a while. So if at least one metric has a bigger change, the algorithm is not considered to have terminated yet.

**Comment by Joslusuca** [comment]
Thanks. Just to avoid any doubt, we could say that f is the Greek letter "phi" in the article...It's ok?

**Comment by julesy89** [comment]
In the paper we refer to it as 
<img width="220" alt="Screen Shot 2021-06-21 at 3 10 29 PM" src="https://user-images.githubusercontent.com/10279009/122814933-d9783200-d2a2-11eb-92bd-1b29e4f588f4.png">

The termination is slightly different implemented than the running metric itself. Please look at the paper for all the details.

**Comment by Joslusuca** [comment]
It means yes, thank you very much!
