### ISSUE TITLE
Request for more references 

### ISSUE THREAD

**Issue by htmehdi** [msu-coinlab/pymoo#165]
Hi,

thank you for the fantastic package that you have developed. I went through the pymoo.org documentation. I couldn't find a use-case related to my issue. I am looking for a couple of examples of how to implement the Pareto set and front functions and how to plot them. Also, I would like to know about the "res.history" contents. how can I extract info from res.history.

I may sound stupid, I am just wondering if there is a defined function to calculate pareto front for simple multi objective optimization. 

I am running my code on an HPC (high-performance computing) system and I would like to know where does the res.history file will be stored. 

Best,

**Comment by julesy89** [comment]
`res.history` contains a complete clone of the algorithm object in each iteration. If you iterate over it you can use `algorithm.pop` to access the population and extract the data you need (design space, objective space, constraint violation, and so on). `res.history` is only stored in memory but of course can be pickled after the run has finished.
Another way is using the `Callback` object which is less memory intensive. Also checkout checkpointing (https://pymoo.org/misc/checkpoint.html).


If we can calculate the Pareto front for an arbitrary multi-objective optimization problem, then we would not need to optimize it anymore. Researchers have developed test problems where we know the front to benchmark algorithms. For arbitrary problems, we execute the algorithm to (hopefully) obtain near-optimal solutions.

**Comment by htmehdi** [comment]
Sorry if my question sounds stupid. I just optimized my two-objective optimization problem with NSGA-II algorithm. I would like to assess the model's performance, and I would like to have a plot as follows. 
![Capture](https://user-images.githubusercontent.com/7489731/122814366-155ec780-d2a2-11eb-81aa-0023d0d38a34.JPG)
I used the object-oriented version of defining my problem, and I have added the following codes to my problem: 

    def _calc_pareto_front(self, *args, **kwargs):
          return func_pf(**kwargs)

    def _calc_pareto_set(self, *args, **kwargs):
          return func_ps(**kwargs)

Could you please help me determine how I can estimate "pf" and "ps" for my model. It is not a mathematical problem with a closed-form solution, and it is a discrete form stochastic-based problem.

**Comment by julesy89** [comment]
That is what I tried to say. It is not possible for an arbitrary optimization problem to mathematically derives the PS and PF. 
If it would be then what would we need optimization for in general?

I recommend using hypervolume (hv) because it does not require the PF.

**Comment by htmehdi** [comment]
Thank you. That is what I have thought that it is not possible. because of that I have tried to extract information from res.history to plot the range of outcomes and solutions. 
One last question, I know that by using the following code we can find the optimal outcome of each generation for objective function. but when I use it for my two objective optimization It just returned the min of one objective not the second one. I want to have min of objective functions in each generation for both objective separately. 

    Val = [e.pop.get("F").min() for e in res.history]

**Comment by julesy89** [comment]
You want to analyze the non-dominated front! Not only the minimum of each objective...

However,`Val = [e.pop.get("F").min(axis=0) for e in res.history]` will do the job.

**Comment by htmehdi** [comment]
Thank you. Greatly appreciate your help and consideration.

**Comment by htmehdi** [comment]
If objectives have different scales, eg. one of them has a range [300-500] and the other one has a range of [100-250]. the min of ["F"] will always select from the second objective. the result of the code I have mentioned is here: 

![Capture](https://user-images.githubusercontent.com/7489731/122822134-ae461080-d2ab-11eb-922c-0d8e8894f0d4.JPG)


It shows the trend of one objective for 30 generations. I want to see the same for the 
second objective and then plot them together to see the non dominated front.

**Comment by julesy89** [comment]
`axis=0` treats each objective independently (applies the operator column-wise). See my code line above or NumPy tutorials.
And as said this only shows the ideal point convergence. You really want to analyze the non-dominated set as a whole.
That is by the way for most algorithms stored in `algorithm.opt`.

**Comment by htmehdi** [comment]
how can I extract it from algorithm.opt.

**Comment by julesy89** [comment]
`algorithm.opt.get("F")`
