### ISSUE TITLE
Collect the least infeasible solution from stored history, without setting return_least_infeasible=True?

### ISSUE THREAD

**Issue by JiQi535** [msu-coinlab/pymoo#166]
Dear pymoo developers and users,

I'm opening this issue to ask if it is possible to collect the least infeasible solution from the stored optimization history during post-analysis. I learnt from the documentation that we can set `return_least_infeasible=True` in the minimize function, but I wonder if we can still get the same information if `return_least_infeasible=True` wasn't set.

Thanks in advance!

**Comment by julesy89** [comment]
Yes, you can. In the result object, you have access to the final population of the algorithm `res.pop`. From there you can extract the least infeasible solution.

**Comment by JiQi535** [comment]
> Yes, you can. In the result object, you have access to the final population of the algorithm `res.pop`. From there you can extract the least infeasible solution.

Thanks very much!
