### ISSUE TITLE
Config file for easier setup of optimization prolbem

### ISSUE THREAD

**Issue by damoclessb** [msu-coinlab/pymoo#168]
Hey Julian,

first of all thank you for the great work you've done with pymoo. I do have question with regards to a good way of specifying the problem for the optimization within pymoo.

Say, we have a complex problem, where lots of parameters can or have to be set such that a number of objectives can be computed. The problem now is that there will be a number of different configurations of the problem that I'd like to investigate, but the parameters for the optimization task can change, i.e. the number of parameters and which of them, constraints, lower and upper boundaries etc. Furthermore, there might be a relatively large number of parameters that are potentially varied by the GA (say more than 20). 

Setting up a new specific problem class each time seems impractical. Have you worked with some kind of config file, from which all the values would have been read automatically or can you think of a way to do that?

Kind regards and thanks for any ideas,
Stefan

**Comment by julesy89** [comment]
I haven't had any project where storing configurations in a file was necessary.
What about saving them in a dictionary in json file and loading them with `json.loads`. 
The dictionary can then be passed to your problem class which retrieves them either trough `**kwargs` or just a single paramter `config`.

```
class MyProblem(Problem):

    def __init__(self, config):
        # access constants and store them
        my_var = config.get("my_var")

        super().__init__(n_var=config.get("n_var"), n_obj=1, n_constr=0, xl=config.get("xl"), xu=config.get("xu"), type_var=anp.double)

    def _evaluate(self, x, out, *args, **kwargs):
        out["F"] = anp.sum(anp.square(x - self.my_var), axis=1)



problem = MyProblem(config=json.loads(fname))

```

**Comment by damoclessb** [comment]
Hey Julian, 

thank you for the fast reply, that was the correct hint and this works fine.

Regards,
Stefan
