### ISSUE TITLE
found a bug in nsga3.py

### ISSUE THREAD

**Issue by weihongjing** [msu-coinlab/pymoo#17]
pop = self.pop[I]
        print(pop.shape)
        print(self.pop.get("is_closest"))
        if len(pop) == 1:
            self.opt = pop
        else:
            self.opt = pop[self.pop.get("is_closest")]

here the last line should be
        self.opt = self.pop[self.pop.get("is_closest")]

**Comment by julesy89** [comment]
Thanks for your comment. Also, infeasible solutions would have been returned if the problem has constrains. 
It should be fixed in the new release 0.3.1. Please let me know if your test case works now!
