### ISSUE TITLE
Pop size / value mismatch : Is it possible to optimize a time series function? 

### ISSUE THREAD

**Issue by iveta-ivanova** [msu-coinlab/pymoo#172]
The functions I am trying to optimize is actually a time series data. **total** and **t** are arrays of 256 values. G is a scalar. 

```
f1 = (1/3)*total*(1+2*((x[0]-x[2])*np.exp(-t/x[1]) + x[2]))
f2 = (1/3)*total*G*(1-((x[0]-x[2])*np.exp(-t/x[1]) + x[2]))
```

When I try to run pymoo with an NSGA-II solver, I get: 

> Exception: Population Set Attribute Error: Number of values and population size do not match!

After some investigation, I see this happens for out['F'], as the value is 12 800 (i.e. 50x256), while the population size is 50. 

Is there any easy way to make pymoo work for such time series / array data or is it just made for optimizing scalar type of functions? 

Many thanks, here's the full code below : 

```
class MyProblem(Problem): 
    total = total
    G = G
    t = t
    
    def __init__(self,total,G,t):                      
        super().__init__(n_var = 3, 
                         n_obj = 2, 
                         n_constr = 0, 
                         xl = np.array([-1., 0., -1.]), 
                         xu = np.array([1., 10., 1.]),
                         elementwise_evaluation = True)
    
    def _evaluate(self, x, out, *args, **kwargs):   # args = [total, G, t]      
        f1 = (1/3)*total*(1+2*((x[0]-x[2])*np.exp(-t/x[1]) + x[2]))
        f2 = (1/3)*total*G*(1-((x[0]-x[2])*np.exp(-t/x[1]) + x[2]))
        
        out["F"] = np.column_stack([f1, f2]) 
       
elementwise_problem = MyProblem(total,G,t)

problem = elementwise_problem 

algorithm = NSGA2(pop_size = 50,
                  n_offspring = 10, 
                  sampling = get_sampling('real_random'),
                  crossover = get_crossover('real_sbx', prob = 0.9, eta = 15),
                  mutation = get_mutation('real_pm',eta = 20),
                  eliminate_duplicates = True)

termination = get_termination("n_gen", 40)

results = minimize(problem,
                   algorithm,
                   termination,
                   seed = 1, 
                   save_history = True,
                   verbose = True)
```

**Comment by julesy89** [comment]
You wil have to carefully design your optimization problem! You have set to optimize 2 objectives. This means with a population size of 50, the `out["F"]` is supposed to have a shape of `(50,2)`.

Be clear about what you are intending to optimize first and then write down your optimization problem on a piece of paper. I assume that somewhere when you consider a time series you need to sum over the time steps `t`.
