### ISSUE TITLE
Is there a upper limit for the No. of constraints or objective functions?

### ISSUE THREAD

**Issue by JiQi535** [msu-coinlab/pymoo#174]
For my optimization problem, the NSGA-II worked very well when I have 2 objective functions and 3 constraints. However, when I enlarge the number of constraints to more than 10 or even over 20, I encountered a memory allocation error in multiprocessing, which I'm now trying to figure out.

In this issue, I want to ask if there is an upper limit for the No. of constraints. I believe that the answer may be algorithm dependent. From the documentation, I learned that there are multi-objective optimization algorithms and many-objective optimization algorithms, though I haven't found comparisons of them in the documentation.

Then, instead of testing all existing algorithms, is there any general rule to select certain algorithm according to this criteria, i.e., maximum No. of constraints? Or is it better to test through all algorithms? Thanks!

**Comment by julesy89** [comment]
All algorithms in pymoo use the feasibility first principle for constraint handling. For very restrictive constraints, this can become an issue. There is quite a bit of research on how environmental survivals can be modified (eps-constraint, for instance) to allow some amount of feasibility. 

Such modifications are not available yet in the current pymoo release, though. The memory error for constraints shall not be related to pymoo itself. For the algorithms the aggregated constraint violation is used, which is the sum of violated constraints for each solution.

**Comment by JiQi535** [comment]
> All algorithms in pymoo use the feasibility first principle for constraint handling. For very restrictive constraints, this can become an issue. There is quite a bit of research on how environmental survivals can be modified (eps-constraint, for instance) to allow some amount of feasibility.
> 
> Such modifications are not available yet in the current pymoo release, though. The memory error for constraints shall not be related to pymoo itself. For the algorithms the aggregated constraint violation is used, which is the sum of violated constraints for each solution.

Thank you for the explanations! I have resolved the memory error by setting save_history=False and save the optimization history in Callback. Deep copies of optimization history turns out to accumulate to a large memory consumption.

I have noticed that pymoo tends to first find the feasible solutions that have zero CV and then optimize the objective functions. From your explanation,  I will take relatively less restrictive constraints. 

Also, since the aggregated constraint violation is used, I found that solution with unbalanced but minimal CV could be chosen as the opt. While the solution with more even but larger CV was dropped. In this case, I'm trying to add penalty to the unbalanced solutions by defining constraints with squared errors instead of absolute errors. Appreciate it if you got more suggestions!
