### ISSUE TITLE
Issue to select best solution out of the results.

### ISSUE THREAD

**Issue by intelligent-222** [msu-coinlab/pymoo#176]
Hi,

First, thank you for the fantastic package. The package is very user-friendly.

I have used the package multiple times and the results were fine and sensible. Recently, in my last couple of runs, the plot shows that there are better solutions rather than the selected results. I haven't change anything in the code or model and just scaled-down one of the objectives by dividing it by 100. 

![download (2)](https://user-images.githubusercontent.com/70038498/128928321-68dedbfd-bbb2-4ce1-b55b-d243ce3d209b.png)

Also, as you can see in the plot, the results without scaling is more distributed in the solution space but the scaled down results are trended around best solution or pareto front. Is there any particular reason for that from an optimization point of view? 

Plot of results before scale down of the objective:
![download (3)](https://user-images.githubusercontent.com/70038498/128928549-0a535f02-c6b7-45eb-bb9c-5e7032624ba6.png)

**Comment by julesy89** [comment]
Thank you for your patience. I am not completely sure if I understand your question. How have you created the first plot? Why are some solutions when changing the scaling dominated? The non-dominated sorting is scaling invariant, and all "Best Solutions" are supposed to be non-dominated too. What am I missing?

**Comment by intelligent-222** [comment]
Thank you for your consideration. The first plot includes the best solutions along with the results of the model. I used the following command to extract all results (solutions)

    df_Res = pd.DataFrame(all_pop.get("F"), columns=[f"F{i+1}" for i in range(problem.n_obj)])

 and then plot them with the best solutions (red dots) in the plot. I have expected to see that the best solutions are the best possible results out of the total population of the solutions. However, as you can see in the following image, there are multiple cases that the results have better solutions than the selected ones
![InkedGithubissue_LI](https://user-images.githubusercontent.com/70038498/132366013-84b4abd5-e682-41dd-951e-1d01f54702be.jpg)
 as best solutions.

**Comment by intelligent-222** [comment]
Let me explain with an example. I plotted my results as I mentioned in previous posts. When I used the following objectives for the two objective optimizations using NSGA II, all the best solutions are non dominant and the best results as you can see in the following plot: 

Objectives:

    obj1 = A
    obj2 = (B+C+D)

![download (3)](https://user-images.githubusercontent.com/70038498/132370057-e3775f9a-afa9-4fa1-8b85-9a2fe886c368.png)

When I changed the scale of the second objective as follow and run the NSGA II model with exact same bounary and criteria, and plotted the results and best solution together, it seems that the model has not selected the non dominant results as best solutions and there are multiple points that looks better that the selected results:

Objectives:

    obj1 = A
    obj2 = (B/150+C/35+D/55)

![InkedGithubissue_LI](https://user-images.githubusercontent.com/70038498/132370470-49d3c531-73fd-417b-ad57-3f2aacde6b5d.jpg)

**Comment by julesy89** [comment]
What are the `Best Solutions`? Is it the ones in `res`? I am not sure what you are plotting.

Feel free to post some example code for a test problem here to elaborate on your issue.

**Comment by intelligent-222** [comment]
The best solutions (red dots) are the values provided by the following command:

    print("Function value: %s" % res.F)

and all solutions (black dots) are the values from the following command:

    df_Res = pd.DataFrame(all_pop.get("F"), columns=[f"F{i+1}" for i in range(problem.n_obj)])

I have plotted them together. As you know, the best functions values (I called them best solutions) suppose to be part of all function values through the entire evolution process. my concern is why there are some points that are visually better than the presented best function values.

I hope it is clear.

**Comment by julesy89** [comment]
Please double-check your code (especially your plots) and look at the example below.
I have redone what you are doing and it seems to work. (is this example representative?)

```
import numpy as np

from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.factory import DTLZ2, Problem
from pymoo.optimize import minimize
from pymoo.visualization.scatter import Scatter


class MyProblem(Problem):

    def __init__(self, scale=None, **kwargs):
        problem = DTLZ2(n_obj=4)
        super().__init__(problem.n_var, 2, 0, problem.xl, problem.xu, **kwargs)
        self.problem = problem
        self.scale = scale

    def _evaluate(self, X, out, *args, **kwargs):
        self.problem._evaluate(X, out, *args, **kwargs)

        F = out["F"]

        scale = self.scale
        if scale is None:
            scale = np.ones(F.shape[1] - 1)

        out["F"] = np.column_stack([F[:, 0], (F[:, 1:] / scale).sum(axis=1)])


problem = MyProblem()

algorithm = NSGA2(pop_size=100)

res_non_scaled = minimize(problem,
               algorithm,
               ('n_gen', 200),
               seed=1,
               verbose=False)

plot = Scatter(title="Non-Scaled")
plot.add(problem.pareto_front(), plot_type="line", color="black", alpha=0.7)
plot.add(res_non_scaled.F, facecolor="none", edgecolor="red")
plot.show()



problem = MyProblem(scale=np.array([100, 20, 1000]))

algorithm = NSGA2(pop_size=100)

res_scaled = minimize(problem,
               algorithm,
               ('n_gen', 200),
               seed=1,
               verbose=False)

plot = Scatter(title="Scaled")
plot.add(problem.pareto_front(), plot_type="line", color="black", alpha=0.7)
plot.add(res_scaled.F, facecolor="none", edgecolor="red")
plot.show()
```

**Comment by intelligent-222** [comment]
If you don't mind I droped "moo" in this command "from pymoo.algorithms.moo.nsga2 import NSGA2" to

   from pymoo.algorithms.nsga2 import NSGA2

Your code is clear, maybe I should explain in more detail. Let me summarize my code here:

    class MultiNGBT(Problem):
  
      def __init__(self):
          super().__init__(n_var=10, n_obj=2, n_constr=0, elementwise_evaluation=True, type_var=int)
          #self.args = args
          self.xl=anp.array([0,0,0,0,0,0,0,0,1,1])
          self.xu = anp.array([16,10,10,10,20,15,16,11,11,11])
  
  
  
      def _evaluate(self, X, out,*args, **kwargs):
  
          
          '''
          Main Functions of the model 
          
          '''
          
          TEUI = np.array(TEUI, dtype=np.float32)
          TEUI=TEUI*0.278 # MJ TO kWh
          
          TTON.append(np.average(TON))
          TTINC.append(np.average(TINC))
          TTDCR.append(np.average(TDCR))
          
          
          obj1 = np.average(TEUI)
          obj2 = (np.average(TON)+average(TINC)+np.average(TDCR))
  
          out["F"] = anp.column_stack([obj1, obj2])
           
    problem = MultiNGBT()
    
    
    method = get_algorithm("nsga2",
                           pop_size=15,
                           sampling=get_sampling("int_random"),
                           crossover=get_crossover("int_sbx", prob=1.0, eta=3.0),
                           mutation=get_mutation("int_pm", eta=3.0),
                           eliminate_duplicates=True,
                           )
    
    
    res = minimize(problem,
                   method,
                   ("n_gen", 40),
                   verbose=True,
                   save_history = True,
                   seed=5)
    print("Function value: %s" % res.F)
    print("Algorithm Object: %s" % res.algorithm)
    print("Final Population Object: %s" % res.pop)
    print("History: %s" % res.history)
    
    all_pop = Population()
  
    for algorithm in res.history:
        all_pop = Population.merge(all_pop, algorithm.off)
    df_Var = pd.DataFrame(all_pop.get("X"), columns=[f"X{i+1}" for i in range(problem.n_var)])
    df_Res = pd.DataFrame(all_pop.get("F"), columns=[f"F{i+1}" for i in range(problem.n_obj)])
    df_Var.to_csv('Variables.csv')
    df_Res.to_csv('Results.csv')

the above-mentioned code works fine. When I replaced the obj2 with the following code the results changed as highlighted in the previous post. 

          
          obj1 = np.average(TEUI)
          obj2 = (np.average(TON)/1984+average(TINC)/465+np.average(TDCR)/325)
  
          out["F"] = anp.column_stack([obj1, obj2])

I am running my code in the High Performance Computing system using multicore processing based on a Linux OS and for some reason, I can not plot the results there and I saved them as csv files and export them to my personal pc to plot the results.

**Comment by julesy89** [comment]
I think something with your plotting or data accumulation is off. I can not spot something that can cause that issue.
What happens if you do a `NonDominatedSorting` on the `all_pop` coming from the scaled objectives?
Are the right solutions selected then?

If you can send me code I can run to reproduce the error let me know.

**Comment by intelligent-222** [comment]
I don't think the issue is with the plotting, as you can see in the following , I have used same data for the both plots:
    
    # Res_b is the output of "print("Function value: %s" % res.F)" 
    Res_b =  ([ 57.61176682, 634.51041667],
     [ 53.78315353, 647.22916667],
     [ 54.6092186 , 637.22916667],
     [ 49.05706787, 735.29166667],
     [ 48.74472046, 961.0625    ],
     [ 48.99613571, 838.5       ],
     [ 48.96141434, 873.32291667],
     [ 48.66884995, 963.32291667],
     [ 48.7763176 , 926.3125    ],
     [ 50.23987198, 681.33333333],
     [ 50.13102341, 729.60416667],
     [ 59.17744827, 627.90625   ],
     [ 48.66479492, 987.32291667])

and the black dots in the plot is the results of the following spreadsheet:

    df_Res = pd.DataFrame(all_pop.get("F"), columns=[f"F{i+1}" for i in range(problem.n_obj)])
    df_Res.to_csv('Results.csv')

I simply used the following code to plot the results:

    plt.subplots(figsize=(16, 10))
    plt.scatter(Res_b['TEUI'],Res_b['COMFORT = TON+TINC+TDCR'], s = 150,color='Red' , label = 'Best Solutions')
    plt.scatter(Results['F1'],Results['F2'], color='black' , label = 'All Solutions for 30 generations with 15 populations (450 results)')
    plt.ylabel('COMFORT = TON+TINC+TDCR', fontsize=18)
    plt.xlabel('TEUI', fontsize=18)
    plt.legend()
    plt.show()

here is the plot of the code without scaling:
![image 1](https://user-images.githubusercontent.com/70038498/132715245-043ffc84-66fd-45a4-bbd7-f857fd240b83.png)

After adding the scaling to the obj2 as follow and running the same code: 

      obj1 = np.average(TEUI)
      obj2 = (np.average(TON)/1984+average(TINC)/465+np.average(TDCR)/325)
      out["F"] = anp.column_stack([obj1, obj2])

I followed the exact same process as mentioned before:

    # Res_b is the output of "print("Function value: %s" % res.F)" 
    Res_b =  ([48.33649826,  3.15794042],
     [69.31764984,  0.5693348 ],
     [50.28026199,  2.28767178],
     [59.32334518,  0.71151133],
     [57.89283371,  1.03700292],
     [49.28619003,  2.74672332],
     [51.2597847 ,  1.93346491],
     [49.56151962 , 2.67546601],
     [52.5424614 ,  1.59333699],
     [53.47738647,  1.51492873],
     [62.18622971,  0.69225877],
     [52.06549072,  1.91733735],
     [66.25148773 , 0.57938779],
     [55.19820023,  1.36639803],
     [63.50837326,  0.63264072])

and the black dots in the plot is the results of the following spreadsheet:

    df_Res = pd.DataFrame(all_pop.get("F"), columns=[f"F{i+1}" for i in range(problem.n_obj)])
    df_Res.to_csv('Results.csv')

I simply used the following code to plot the results:

    plt.subplots(figsize=(16, 10))
    plt.scatter(Res_b['TEUI'],Res_b['COMFORT = TON/1900+TINC/25+TDCR/30'], s = 150,color='Red' , label = 'Best Solutions')
    plt.scatter(Results['F1'],Results['F2'], color='black' , label = 'All Solutions for 30 generations with 15 populations (450 results)')
    plt.ylabel('COMFORT = TON/1900+TINC/25+TDCR/30', fontsize=18)
    plt.xlabel('TEUI', fontsize=18)
    plt.legend()
    plt.show()

here is the plot of the code without scaling:
![image 2](https://user-images.githubusercontent.com/70038498/132715736-e06c1501-eeec-445b-9e0f-0467d3c2008e.png)


Hopefully, the explanation is clear. 

Can you elaborate more on the "What happens if you do a NonDominatedSorting on the all_pop coming from the scaled objectives?" could you please help me to find that where should I add this command. I strongly believe it may help to solve the problem.

I greatly appreciate all your help and consideration.

**Comment by julesy89** [comment]
See the code below (assuming all objectives are minimized).

```
import matplotlib.pyplot as plt

import numpy as np
from pymoo.util.nds.non_dominated_sorting import NonDominatedSorting

F = np.random.random((100, 2))

nds = NonDominatedSorting().do(F, only_non_dominated_front=True)

plt.scatter(F[:, 0], F[:, 1], color="black", alpha=0.5)
plt.scatter(F[nds, 0], F[nds, 1], color="red")
plt.show()


```

**Comment by intelligent-222** [comment]
Thank you very much. I think it works and it gave me the "nds" which I believe can be considered as the best solution or best function values for my problem. 

![download](https://user-images.githubusercontent.com/70038498/133096630-702dc2b8-b2ff-4381-b694-0ee8ac2e55b7.png)

**Comment by julesy89** [comment]
Great! 
(still wondering why only executing the algorithm should not work though)

**Comment by intelligent-222** [comment]
maybe the scaling process reduces the objective range significantly and it causes confusion. not sure, but since the issue happened after scaling the objective I came to this conclusion. 

Thank you for all your help and support. Also, is there any citation that I can use for this package in my paper?

**Comment by julesy89** [comment]
I am glad it has been resolved.

Yes, https://ieeexplore.ieee.org/document/9078759

Julian
