### ISSUE TITLE
Problem when usying pyinstaller

### ISSUE THREAD

**Issue by FoxBearBear** [msu-coinlab/pymoo#178]
I am tyring to bundle pymoo in an exe but when running the optimization it gives me :l

**("No module named 'pymoo.cython.non_dominated_sorting'",)**

I've tried to compile the code but it did not worked so far.

**Comment by julesy89** [comment]
I have tried `pyinstaller` it a long time ago to create a package and could not get it to work. It is for sure possible and how to deal with a package using Cython compiled code is probably the right keywords to search for.

Please let me and others know here if you have solved it and what the solution was!

**Comment by fbattini** [comment]
Hi @julesy89,
I am using pymoo for an optimization. I have a GUI developed with Tkinter and I use pyinstaller to get an exe file to distribute. Everything works fine when I run my script from python but when I run the exe file it shows the same error reported by @FoxBearBear : 
**ModuleNotFoundError: No module named 'pymoo.cython.non_dominated_sorting'**

Going through similar issues of pyinstaller I tried to give pymoo or pymoo.cython.non_dominated_sorting as hidden file to overcome this problem but I didn't find a solution. Could you or anyone please help me?
