### ISSUE TITLE
Running bug when calculating hv

### ISSUE THREAD

**Issue by EvaFlower** [msu-coinlab/pymoo#18]
pymoo version: 0.3.0  
File "../py36/lib/python3.6/site-packages/pymoo/model/indicator.py", line 21, in calc
    return self._calc(F)
  File "../py36/lib/python3.6/site-packages/pymoo/indicators/hv.py", line 43, in _calc
    val = hv.compute(_F)
  File "../py36/lib/python3.6/site-packages/pymoo/indicators/hv.py", line 117, in compute
    hyperVolume = self.hvRecursive(dimensions - 1, len(relevantPoints), bounds)
  File "../py36/lib/python3.6/site-packages/pymoo/indicators/hv.py", line 153, in hvRecursive
    while q.cargo != None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I think "q.cargo != None" may be:  
q.cargo is not None

**Comment by EvaFlower** [comment]
Hi there, I used the pymoo 0.3.0. For the newest version, the failure refers to:
https://github.com/msu-coinlab/pymoo/blob/86cd806a497072e83eae2ebfc1fc1f54971a4517/pymoo/vendor/hv.py#L108

I think the failure is because like when **q.cargo = [0.5, 0.5, None]**, **q.cargo != None** will get **[True, True, False]**, that is what the error "The truth value of an array with more than one element is ambiguous" means. So my suggestion is to revise it as **q.cargo is not None**

**Comment by EvaFlower** [comment]
Hi there, I am using the pymoo 0.3.0. The failure refers to the newest version as followings:
https://github.com/msu-coinlab/pymoo/blob/86cd806a497072e83eae2ebfc1fc1f54971a4517/pymoo/vendor/hv.py#L108

**Comment by spyridon-amp** [comment]
My code breaks in the same line when calculating the hypervolume of data with >= 3 dimensions.
Here is an example:

`data = np.array([[0,3, 0], [1,2, 0], [2,1, 0], [3,0, 0]]).astype('double')
ref_point=np.array([3.0, 3.0, 0])
hv = get_performance_indicator('hv', ref_point=ref_point)
hypervolume = hv.calc(data)
`

`~\AppData\Local\Continuum\anaconda3\lib\site-packages\pymoo\vendor\hv.py in hvRecursive(self, dimIndex, length, bounds)
    106             p = sentinel
    107             q = p.prev[dimIndex]
--> 108             while q.cargo != None:
    109                 if q.ignore < dimIndex:
    110                     q.ignore = 0

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by julesy89** [comment]
Thanks for the concrete input. The HV implementation is from another vendor library.
I will contact the author about this issue.

**Comment by julesy89** [comment]
The author of the implementation has provided me the fix. 

You can replace the vendor hv library by the current version on GitHub to make it work: 
https://raw.githubusercontent.com/msu-coinlab/pymoo/master/pymoo/vendor/hv.py


It will also be fixed in the next release of pymoo. (probably some time in March)

**Comment by julesy89** [comment]
It should work now with pymoo 0.4.0.
