### ISSUE TITLE
[Question] NSGA2 and 3 algorithm are good methods for my project? 

### ISSUE THREAD

**Issue by jongyook2** [msu-coinlab/pymoo#20]
Hello, 
I'm searching optimizing algorithms for my project. 
my project has one or two objectives(ex. x+y+z or px+qy+rz) and 18 constraint functions(ex. a1x+b1y+c1z-d1=0 -> equality) 
Is it possible to find solutions by using NSGA2 or 3? If it is possible, which algorithm is the best for my project?

Thank you in advance!!!

**Comment by julesy89** [comment]
A good choice for 2 objectives is NSGA-II. If more than 2 objectives then NSGA-III.

For both algorithms the constraint handling is more fundamental (parameter-less constraint handling). If most of your search space is infeasible you might need better constraint handling.

**Comment by julesy89** [comment]
And if it has only one objective you can use the GA implementation we provide as well.

Our algorithms are listed here:
http://pymoo.org/algorithms/index.html

**Comment by jongyook2** [comment]
Thank you very much!
