### ISSUE TITLE
[Question] Error

### ISSUE THREAD

**Issue by jongyook2** [msu-coinlab/pymoo#21]
Hello~
I'm following getting started(https://pymoo.org/getting_started.html) changing constraints and objective, but it shows error code below
     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-107-ee2ea22fbf6f> in <module>
     13                pf=problem.pareto_front(use_cache=False),
     14                save_history=True,
---> 15                verbose=True)

C:\Users\Farmboy\Anaconda3\envs\flavor\lib\site-packages\pymoo\optimize.py in minimize(problem, algorithm, termination, **kwargs)
     56 
     57     # actually execute the algorithm
---> 58     res = algorithm.solve()
     59 
     60     # store the copied algorithm in the result object

C:\Users\Farmboy\Anaconda3\envs\flavor\lib\site-packages\pymoo\model\algorithm.py in solve(self)
    152 
    153         # call the algorithm to solve the problem
--> 154         self._solve(self.problem)
    155 
    156         # store the resulting population

C:\Users\Farmboy\Anaconda3\envs\flavor\lib\site-packages\pymoo\model\algorithm.py in _solve(self, problem)
    201         self.n_gen = 1
    202         self._initialize()
--> 203         self._each_iteration(self, first=True)
    204 
    205         # while termination criterion not fulfilled

C:\Users\Farmboy\Anaconda3\envs\flavor\lib\site-packages\pymoo\model\algorithm.py in _each_iteration(self, D, first, **kwargs)
    216         # display the output if defined by the algorithm
    217         if self.verbose and self.func_display_attrs is not None:
--> 218             disp = self.func_display_attrs(self.problem, self.evaluator, self, self.pf)
    219             if disp is not None:
    220                 self._display(disp, header=first)

C:\Users\Farmboy\Anaconda3\envs\flavor\lib\site-packages\pymoo\util\display.py in disp_multi_objective(problem, evaluator, algorithm, pf)
     70     if len(feasible) > 0:
     71         if pf is not None:
---> 72             attrs.append(('igd', format_float(IGD(pf).calc(F[feasible])), width))
     73             attrs.append(('gd', format_float(GD(pf).calc(F[feasible])), width))
     74             if problem.n_obj == 2:

C:\Users\Farmboy\Anaconda3\envs\flavor\lib\site-packages\pymoo\model\indicator.py in calc(self, F)
     47         self.range = np.ones(self.n_dim)
     48 
---> 49         return self._calc(F)
     50 
     51     @abc.abstractmethod

C:\Users\Farmboy\Anaconda3\envs\flavor\lib\site-packages\pymoo\performance_indicator\distance_indicator.py in _calc(self, F)
     24 
     25     def _calc(self, F):
---> 26         D = vectorized_cdist(self.pf, F, func_dist=self.dist_func, norm=self.range)
     27         return np.mean(np.min(D, axis=self.axis))
     28 

C:\Users\Farmboy\Anaconda3\envs\flavor\lib\site-packages\pymoo\util\misc.py in vectorized_cdist(A, B, func_dist, **kwargs)
    100     v = np.tile(B, (A.shape[0], 1))
    101 
--> 102     D = func_dist(u, v, **kwargs)
    103     M = np.reshape(D, (A.shape[0], B.shape[0]))
    104     return M

C:\Users\Farmboy\Anaconda3\envs\flavor\lib\site-packages\pymoo\performance_indicator\distance_indicator.py in euclidean_distance(a, b, norm)
      6 
      7 def euclidean_distance(a, b, norm=None):
----> 8     return np.sqrt((((a - b) / norm) ** 2).sum(axis=1))
      9 
     10 

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

How to solve it? (obj: 1 constr: 4) 
Thank you in advance.

**Comment by julesy89** [comment]
what pymoo version are you using? 0.3.0 or 0.3.1? 
you can see it by using 
`pip list`

To update pymoo please use
`pip intall -U pymoo`

And what NumPy version are you using?

**Comment by jongyook2** [comment]
Pymoo -> 0.3.1
Numpy -> 1.15.4

Thank you

**Comment by julesy89** [comment]
Can you replace the minimize statement by:
```

res = minimize(problem,
               algorithm,
               termination,
               seed=1,
               pf=None,
               save_history=True,
               verbose=True)
```

Does that work for you?

**Comment by jongyook2** [comment]
Yes, it works. 
I will check the pf option.
Thank you!
