### ISSUE TITLE
Runtime error when running parallel experiments on windows os

### ISSUE THREAD

**Issue by wongsycheryl** [msu-coinlab/pymoo#23]
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.
            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:
                if __name__ == '__main__':
                    freeze_support()
                    ...
            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.

This error comes up when trying to run parallelization on windows but not when I run on linux.

**Comment by julesy89** [comment]
Can you provide me some code which lets me reproduce your error?
How do you parallelize it your experiment?

I am working on MacOS but I do have access to a Windows machine to check it out.

**Comment by wongsycheryl** [comment]
I ran the example given on the pymoo documentation, screenshots below

![pymoo_windows_error_1](https://user-images.githubusercontent.com/26615980/66012415-ab185900-e4f9-11e9-8f42-259348a2c60d.PNG)

![pymoo_windows_error_2](https://user-images.githubusercontent.com/26615980/66012440-c71bfa80-e4f9-11e9-81a5-f4a38f6b5a1c.PNG)

**Comment by julesy89** [comment]
Thanks for your example. I will have a look into it. 
I did not check the parallel evaluation on a Windows machine. Thanks for letting me know!

**Comment by julesy89** [comment]
I was able to reproduce the error. I think it is not related to the implementation in the framework, but related to how you run your example.

It is related to the following post on StackOverflow:
https://stackoverflow.com/questions/24374288/where-to-put-freeze-support-in-a-python-script

This throws an error:

```
import numpy as np
from pymoo.model.problem import Problem


class MyProblem(Problem):

	def __init__(self, **kwargs):
		super().__init__(n_var=10, n_obj=1, n_constr=0, xl=-5, xu=5, 
					elementwise_evaluation=True, **kwargs)

	def _evaluate(self, x, out, *args, **kwargs):
		out["F"] = (x ** 2).sum()

			 
problem = MyProblem(parallelization = ("threads", 4))
X = np.random.random((10000, problem.n_var))
F = problem.evaluate(X)
print(F)

```


And this does not:

```
import numpy as np
from pymoo.model.problem import Problem


class MyProblem(Problem):

	def __init__(self, **kwargs):
		super().__init__(n_var=10, n_obj=1, n_constr=0, xl=-5, xu=5, 
					elementwise_evaluation=True, **kwargs)

	def _evaluate(self, x, out, *args, **kwargs):
		out["F"] = (x ** 2).sum()

			 
if __name__ == '__main__':
	problem = MyProblem(parallelization = ("threads", 4))
	X = np.random.random((10000, problem.n_var))
	F = problem.evaluate(X)
	print(F)

```


Which means on Windows your multiprocessing code must be in a main method.
Please let me know if this works for you.

**Comment by wongsycheryl** [comment]
Yes it works for me, thank you! :)
