### ISSUE TITLE
New problem sets

### ISSUE THREAD

**Issue by ClaudioLucioLopes** [msu-coinlab/pymoo#26]
Is there any plans to incorporate new problem sets: WFG and MaF for example?

**Comment by julesy89** [comment]
We are going to release a new version soon. However, no new test problems will be included. 
In general, having more test problems is always better. But we did not put new test suites on our agenda yet.
We are searching for people willing to contribute anytime. If you are interested in coding some of them please let us know.

**Comment by prasadovhal** [comment]
I was trying Fonseca–Fleming function but I am facing the following issue. 

Exception: Population Set Attribute Error: Number of values and population size do not match!

**Comment by julesy89** [comment]
Make sure whatever you store in `out["F"]` has the size as `len(X)`.

Otherwise, I would need a source code snippet to reproduce your error.

**Comment by prasadovhal** [comment]
Here it is.

class MyProblem(Problem):

    def __init__(self):
        super().__init__(n_var=3,
                         n_obj=2,
                         n_constr=0,
                         xl=anp.array([-2,-2,2]),
                         xu=anp.array([2,2,2]))

    def _evaluate(self, x, out, *args, **kwargs):
        a,b = 0,0
        for i in range(self.n_var):
            a += (x[i] - 1 / np.sqrt(self.n_var))**2
            b += (x[i] + 1 / np.sqrt(self.n_var))**2

        f1 = 1 - np.exp(-a)
        f2 = 1 - np.exp(-b)
        #g1 = 0.000001 * x
        #g2 = 0.000001 * x

        out["F"] = anp.column_stack([f1, f2])
        #out["G"] = anp.column_stack([g1, g2])


    def _calc_pareto_front(self, flatten=True, **kwargs):
        f1_a = np.linspace(0.1**2, 0.4**2, 100)
        f2_a = (np.sqrt(f1_a) - 1)**2

        f1_b = np.linspace(0.6**2, 0.9**2, 100)
        f2_b = (np.sqrt(f1_b) - 1)**2

        a, b = np.column_stack([f1_a, f2_a]), np.column_stack([f1_b, f2_b])
        return stack(a, b, flatten=flatten)

    def _calc_pareto_set(self, flatten=True, **kwargs):
        x1_a = np.linspace(0.1, 0.4, 50)
        x1_b = np.linspace(0.6, 0.9, 50)
        x2 = np.zeros(50)

        a, b = np.column_stack([x1_a, x2]), np.column_stack([x1_b, x2])
        return stack(a,b, flatten=flatten)

problem = MyProblem()

algorithm = NSGA2(pop_size=100, eliminate_duplicates=True)

res = minimize(problem,
               algorithm,
               ('n_gen', 200),
               seed=1,
               verbose=True)

**Comment by julesy89** [comment]
Your bounds are incorrect. I guess the last `xl` should be a `0.2` as the others.
Moreover, they need to be all floats and not integer.

In your evaluation you assume only a single individual is provided. However, by default the whole population is passed to the evaluation function to allow parallelization.
To evaluate each individual serialized use `elementwise_evaluation=True`.

Fixing all of that the problem seems to run. The modifications I have made are shown below.


```
import numpy as np

from pymoo.algorithms.nsga2 import NSGA2
from pymoo.model.problem import Problem
from pymoo.optimize import minimize


class MyProblem(Problem):
    def __init__(self):
        super().__init__(n_var=3,
                         n_obj=2,
                         n_constr=0,
                         xl=np.array([-2.0, -2.0, -2.0]),
                         xu=np.array([2.0, 2.0, 2.0]),
                         elementwise_evaluation=True)

    def _evaluate(self, x, out, *args, **kwargs):
        a, b = 0, 0

        for i in range(self.n_var):
            a += (x[i] - 1 / np.sqrt(self.n_var)) ** 2
            b += (x[i] + 1 / np.sqrt(self.n_var)) ** 2

        f1 = 1 - np.exp(-a)
        f2 = 1 - np.exp(-b)

        out["F"] = [f1, f2]


problem = MyProblem()

algorithm = NSGA2(pop_size=100, eliminate_duplicates=True)

res = minimize(problem,
               algorithm,
               ('n_gen', 200),
               seed=1,
               verbose=True)

```

**Comment by julesy89** [comment]
Anyway, the pymoo way of coding up your problem is:

```
class MyProblem(Problem):
    def __init__(self):
        super().__init__(n_var=3,
                         n_obj=2,
                         n_constr=0,
                         xl=np.array([-2.0, -2.0, -2.0]),
                         xu=np.array([2.0, 2.0, 2.0]))

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = 1 - np.exp(-((x - 1 / np.sqrt(self.n_var)) ** 2).sum(axis=1))
        f2 = 1 - np.exp(-((x + 1 / np.sqrt(self.n_var)) ** 2).sum(axis=1))
        out["F"] = np.column_stack([f1, f2])
```

**Comment by prasadovhal** [comment]
Thank you so much. That really helped. and got the way to solve new problems also. Really appreciated.
