### ISSUE TITLE
First run issue

### ISSUE THREAD

**Issue by MattD92** [msu-coinlab/pymoo#27]
Good morning,
I installed pymoo using pip on a win10 pc. 
When I run one of the example (I started with the one in the readme file) I have always this error:

```
File "<__array_function__ internals>", line 4, in any
NameError: name 'dispatcher' is not defined
```

How can I fix it? 
Thank you!

EDIT
I'm really sorry,
I just figured out that something broke my anaconda installation.
I solved reinstalling it.

**Comment by julesy89** [comment]
No problem.
