### ISSUE TITLE
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)

### ISSUE THREAD

**Issue by raeessrk** [msu-coinlab/pymoo#28]
Kindly help me in the above error occurs when I am using a pymoo multiobjective optimization class for my custom data set.

**Comment by julesy89** [comment]
We will need some more information to be able to reproduce the error. Please provide a script of something that helps us to investigate this issue. 
You can also contact me via email if you do not like to post data sets or your problem description here on GitHub.
