### ISSUE TITLE
a minor error in pymoo.org 

### ISSUE THREAD

**Issue by aflyingnoob** [msu-coinlab/pymoo#29]
![image](https://user-images.githubusercontent.com/30976978/68390057-6e4a1c80-019f-11ea-98d4-b6e1bd91ee74.png)

**Comment by aflyingnoob** [comment]
Bottom of this page [Performance Tracking](https://pymoo.org/getting_started.html)

**Comment by julesy89** [comment]
Thank you very much for pointing this out. We try to keep our documentation as bug free as possible and feedback like this helps us to further improve.

I have already fixed it on the homepage.
