### ISSUE TITLE
using multi process

### ISSUE THREAD

**Issue by pawopawo** [msu-coinlab/pymoo#32]
I am running NSGA-2 with multiple threads, but I found that the `x` in the `_evaluate` function is different in each thread. I want each thread to use the same `x`.  Whether `x` is generated using the `random` function? if that is the case, Add `random.seed()` to control all threads to produce the same `x`? 
In addition, where do the parameters `x` and `out` of the `_evaluate` function come from? What are the functions of the parameters `n_var, n_obj, n_constr, lb, ub`?

![image](https://user-images.githubusercontent.com/38682321/69540184-00845a00-0fc1-11ea-949e-bb69f3e15145.png)

**Comment by julesy89** [comment]
I am not sure if I fully understood what you are planing to do. The support in `pymoo` for multithreading is that in each thread a different `x` is evaluated. 

But you like to use several threads to evaluate a single `x`? If this is the case that is simply part of your `_evaluate` function which spawns a couple of threads for each `x`.

For the basics, I like to refer to our getting started guide: https://pymoo.org/getting_started.html
There, we explain how a problem maps to code and how to define the number of variables `n_var`, number of objectives `n_obj`, number of constraints `n_constr` and box constraints `xl` and `xu`.

**Comment by pawopawo** [comment]
I'm sorry to reply so late!
Yes, I want to use several threads to evaluate a single `x`. In order to speed up the calculation of `out ["F"]`, multiple threads are used, so each thread needs to evaluate a single `x`. I don't know what is the meaning of `spawns a couple of threads for each x`.
Hope to receive your reply
