### ISSUE TITLE
Initialize population of choice or access the initialized population by toolbox?

### ISSUE THREAD

**Issue by nagpalh** [msu-coinlab/pymoo#33]
Hi,

Is there any way to access the initial population defined by the toolbox. Apart from the decision variable, I have one additional variable in the objective function whose value depend upon the decision variable and comes from a software. In other words, I pass the initial population of decision variables to the software, get the values of other variable and then evaluate the objective function. Is there a way that I can get initial population before using "minimize" function?

Thanks in advance.

**Comment by julesy89** [comment]
Yes there is you can directly provide values to the initial population. 

For instance, 

```
import numpy as np

from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_problem
from pymoo.model.evaluator import Evaluator
from pymoo.model.population import Population
from pymoo.optimize import minimize

problem = get_problem("zdt2")

X = np.random.random((300, problem.n_var))

algorithm = NSGA2(pop_size=100, sampling=X)

minimize(problem,
         algorithm,
         ('n_gen', 10),
         seed=1,
         verbose=True)
```

will use the X you have sampled for the initial population. If you further provide `F` and `CV` values they are not evaluated again. (you have to pass a population object for that)


```
pop = Population().new("X", X)
Evaluator().eval(problem, pop)

algorithm = NSGA2(pop_size=100, sampling=pop)

minimize(problem,
         algorithm,
         ('n_gen', 10),
         seed=1,
         verbose=True)
```


Your function evaluation question is related to the problem formulation. If the decision variables `x` are used to calculate new variables `y`. And then an evaluator takes `x` and `y` to give you an objective value, then pymoo only cares about the variable it can influence which is `x`.
That means `y` would be nothing else than a function call, but not an inherent part of the optimization variables.

**Comment by nagpalh** [comment]
Thank you very much @julesy89 . This is very helpful.
