### ISSUE TITLE
nsga3 algorithm evolution problem

### ISSUE THREAD

**Issue by pawopawo** [msu-coinlab/pymoo#35]
```
class NSGA3(GeneticAlgorithm):

    def __init__(self,
                 ref_dirs,
                 pop_size=None,
                 sampling=IntegerFromFloatSampling(clazz=FloatRandomSampling),
                 selection=TournamentSelection(func_comp=comp_by_cv_then_random),
                 crossover=SimulatedBinaryCrossover(eta=30, prob=1.0),
                 mutation=PolynomialMutation(eta=20, prob=None),
                 eliminate_duplicates=True,
                 n_offsprings=None,
                 display=MultiObjectiveDisplay(),
                 **kwargs)
```
I initialized an nsga3 in the above way. I want my structure to be made up of integers, so I use `sampling = IntegerFromFloatSampling (clazz = FloatRandomSampling)` to initialize the population. But the structure in the first `offspring` evolved has decimals.

Seems to be caused by `PolynomialMutation`. Doesn't support integer mutation?

Hope for help

**Comment by julesy89** [comment]
We already provide an example for discrete (integer) encoded variables on the homepage:
https://pymoo.org/tutorial/discrete_problem.html

Does that solve your problem?

**Comment by pawopawo** [comment]
Thank you very much.
