### ISSUE TITLE
Does algorithms include nsga3-part2

### ISSUE THREAD

**Issue by bofengshuimen77** [msu-coinlab/pymoo#36]
I only found "selection=TournamentSelection(func_comp=comp_by_cv_then_random)" in nsga3.py. But I didn't find code about addition of new reference points and deletion of existing reference points，which  are also  included in the paper, An Evolutionary Many-Objective Optimization Algorithm Using Reference-Point Based Nondominated Sorting Approach,
Part {II}: Handling Constraints and Extending to an Adaptive Approach.
Looking forward to your reply.

@ARTICLE{nsga3-part2,
author={H. Jain and K. Deb},
journal={IEEE Transactions on Evolutionary Computation},
title={An Evolutionary Many-Objective Optimization Algorithm Using Reference-Point Based Nondominated Sorting Approach,
Part {II}: Handling Constraints and Extending to an Adaptive Approach},
year={2014},
volume={18},
number={4},
pages={602-622},
ISSN={1089-778X},
month={Aug},
}

**Comment by julesy89** [comment]
In our implementing all references directions are kept during the whole run of NSGA-3. 
So far, this extension of NSGA-3 is not implemented. If you are interested in contributing to our framework and adding this as a feature please let me know.

However, this was more or less a naive solution to deal with different Pareto front shapes where parts in the objective space do not contain any feasible non-dominated solution. We also started to work further on gap finding methods in general. In fact, during the run of the algorithm the challenge is to decide whether it is truly a gap or just no solution close to the reference direction has been found yet.

Julian
