### ISSUE TITLE
When using ‘Problem’ class,where should the target function be set if it has priority or weight?

### ISSUE THREAD

**Issue by twodonkeys** [msu-coinlab/pymoo#40]
Hi, I want to use this library to solve a multi-objective programming problem, where should the target function be set if it has priority or weight?I'm new to multi-objective programming, maybe it's a silly question ^^.

**Comment by julesy89** [comment]
In traditional multi-objective optimization there is no priority or weight. That is an important aspect of the overall concept. 
Weights or priorities are used for the purpose of scalarization to in fact solve a multi-objective problem in a single-objective manner.

You can have a look at our getting started guide: 
https://pymoo.org/getting_started.html
