### ISSUE TITLE
[Feature Request] resuming an algorithm after termination

### ISSUE THREAD

**Issue by mbabadi** [msu-coinlab/pymoo#45]
This feature is particularly important for checkpointing and resuming long-running jobs. I wonder whether this feature already exists but it has slipped my attention?

**Comment by julesy89** [comment]
It does not exist directly and I did not have any feature request regarding that yet.
A simply fix is to use the same algorithm object, but provide the final population as the initial population.


```
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import ZDT1
from pymoo.factory import get_sampling, get_crossover, get_mutation
from pymoo.optimize import minimize

algorithm = NSGA2(
    pop_size=40,
    n_offsprings=10,
    sampling=get_sampling("real_random"),
    crossover=get_crossover("real_sbx", prob=0.9, eta=15),
    mutation=get_mutation("real_pm", eta=20),
    eliminate_duplicates=True
)

problem = ZDT1()

res = minimize(problem,
               algorithm,
               ('n_gen', 40),
               seed=1,
               pf=problem.pareto_front(use_cache=False),
               save_history=True,
               verbose=True)

algorithm.sampling = res.algorithm.pop

res = minimize(problem,
               algorithm,
               ('n_gen', 20),
               seed=1,
               pf=problem.pareto_front(use_cache=False),
               save_history=True,
               verbose=True)

```

Does that work for you?

**Comment by mbabadi** [comment]
Thank you very much for your quick reply Julian! I realized the solution a few minutes ago once I took a deeper dive into the API. I came here to post the solution and close the issue but you already did it :) thanks again!
