### ISSUE TITLE
Problem notebooks not showing up in TOC in docs

### ISSUE THREAD

**Issue by JoshKarpel** [msu-coinlab/pymoo#47]
Based on the RST in https://github.com/JoshKarpel/pymoo/blob/373bd573f472b41a1ea06f16568398000b8ea81a/doc/source/problems/index.ipynb, I would expect the various example notebooks listed in the raw cell to show up in the TOC tree from  http://pymoo.org/problems/index.html , but that doesn't seem to be the case. I think the intent was to make the pages visible from the problems index page, but as far as I can tell they aren't.

**Comment by julesy89** [comment]
Did you figure it out? You have to add the problems two times. Once in the overview table and once in the TOC.

**Comment by JoshKarpel** [comment]
Sorry, I never got around to taking a look at it. Feel free to close the issue if you've got it working now.
