### ISSUE TITLE
Possibility to enforce hard constraints

### ISSUE THREAD

**Issue by renatobellotti** [msu-coinlab/pymoo#50]
Hi,
I'm trying to solve an optimisation problem (obviously). Unfortunately, I don't have a single feasible solution in my final generation. Is it possible to enforce the constraints in a "hard" way? I'm thinking about only adding individuals that fulfil the constraints.

**Comment by julesy89** [comment]
If you like to have returned the least infeasible solutions feel free to do:
`algorithm = GA(pop_size=5, return_least_infeasible=True)`

Is it an equality constraint or a very strict inequality constraint? Those can be challenging to satisfy with a GA.
However, repair operators can be an option to handle them efficiently and force them to be satisfied by every individual.
An example is provided here: https://pymoo.org/misc/constraint_handling.html

Does this help?

**Comment by renatobellotti** [comment]
Thanks for your fast answer.
Let me explain my problem in more detail. I'm trying to optimise a particle accelerator. Our x values are the settings that our operation team can apply to the machine. We have a simulation code f that maps the settings to physical quantities like beams size and energy.
We have a constraint on the beamsize: At some positions, we want 2 < f(x) < 5. This is not fulfilled for any individual x in the last generation.

If I understood the documentation correctly, repair functions work only if the constraints are applied to the x values, not to our f(x).

Is there another way to enforce that only configurations that fulfil 2 <= f(x) <= 5 are in our generations? Or do I have to write a repair function that randomly samples x configurations until a feasible one is found?

**Comment by julesy89** [comment]
What you desire to do is introducing a constraint in the objective space.
For example for a sphere function that would be:

```
class SphereWithConstraints(Problem):

    def __init__(self, n_var=10):
        super().__init__(n_var=n_var, n_obj=1, n_constr=2, xl=-0, xu=1, type_var=np.double)

    def _evaluate(self, x, out, *args, **kwargs):
        f = np.sum(np.square(x - 0.5), axis=1)
        g1 = 2 - f  # this constraints makes sure that f >= 2
        g2 = f - 5  # this makes sure f <= 5
        out["F"] = f
        out["G"] = np.column_stack([g1, g2])
```

Do not forget to set `n_constr` in your problem.

**Comment by renatobellotti** [comment]
This is exactly what I'm doing. Nevertheless, I don't get feasible individuals. Is there anything else I can do?

**Comment by renatobellotti** [comment]
Is it possible to initialise the population separately to make sure all individuals are feasible, and then hand it to the `minimze()` function or somewhere else?

**Comment by renatobellotti** [comment]
Ok, I was able to solve my problem by adding more individuals.

I'm still interested in manual initialisation. I'll open a separate issue.

Thanks for you help!
