### ISSUE TITLE
Manual initialisation

### ISSUE THREAD

**Issue by renatobellotti** [msu-coinlab/pymoo#51]
Is it possible to initialise the population manually, e. g. by giving an array to the `Problem` constructor?

**Comment by julesy89** [comment]
Yes you can do that. However, this is not part of the problem but part of your algorithm.
All genetic algorithms in pymoo accept different objects for sampling.

You can find a usage file here: 
https://github.com/msu-coinlab/pymoo/blob/master/pymoo/usage/algorithms/usage_initial_population.py

This shows two possible other ways instead of using a `Sampling` object.

a) You just pass the `X` values as a NumPy matrix
b) You pass an `population` object (here the individuals might have been already evaluated)

**Comment by renatobellotti** [comment]
Thank you very much for your answer! I think this information is valuable for many people. It would be a great addition to the documentation.

**Comment by julesy89** [comment]
Yes, you are now the second or third person approaching me with this. 

Where at our online documentation would you have had a look at or do you think is appropriate to discuss such things?
Do you think FAQ for those questions would make sense?

**Comment by renatobellotti** [comment]
I think it would be a good idea to add it as an additional tutorial. When I start to use a new package, I usually look for introductory guides, and then for tutorials on specific questions. The tutorials already are something like an FAQ with code examples, so I don't think a separated section is necessary.

The tutorial section itself is perhaps a bit hidden. Right now, it is at the bottom of the page. I think it would be helpful to move it above the "Algorithms" box in the `Features` section. Then it would be the first thing to see after reading through the "Getting started" page (which, by the way, is an excellent resource!).

Since we're already talking about documentation, I have another suggestion. For me, it is not clear what the dictionary keys in the `out` dict and the result are. One can infer the meaning of `F` and `G` in the getting started guide, but in my opinion a small table with all the keys and their meaning would clarify things even more. It could be added to the getting started guide.

Thanks for taking interest and writing such a nice package! :)

**Comment by julesy89** [comment]
Yes, I totally agree there is some room for improvement regarding the documentation. The challenge is to still keep everything organized, but do make important information as visible as possible.

For instance, there is a documentation for the result object under `Miscellaneous`:
https://pymoo.org/misc/results.html

But probably it should be directly or close to algorithms...

Thanks for all your input and positive feedback!

**Comment by julesy89** [comment]
I have added it to the documentation and created a new feature cell, called `Customization`.
Hope that is more clear now.

**Comment by renatobellotti** [comment]
Thanks for the improvement!
