### ISSUE TITLE
Can I save population in every 1000 evaluations?

### ISSUE THREAD

**Issue by Peng-YM** [msu-coinlab/pymoo#52]
Currently, pymoo saves the population to `res.history` in every generation. However, when comparing different algorithms, the number of function evaluations in each generation are usually different. 

When comparing the convergence property of different algorithms, I would like to compare the population in 1000 (or other pre-specified numbers)  evaluations. It there any way to do that? Thanks in advance!

**Comment by julesy89** [comment]
The history saves the current algorithm object by making use of the `deepcopy` method of Python. The `population` object is part of it and contains the surviving individuals if it is a `GA` or maybe another representative set of solutions depending on the algorithm.

One way of doing the comparison is to plot the convergence curve with the x-axis representing the number of function evaluations. The number of function evaluations is stored in the `algorithm.evaluator.n_eval`. See the example below.

If you only like to compare the final result you can simply set `("n_evals", 1000)` to the specified number and the algorithm will terminate close to this maximum (It might be slightly more. The algorithm will not start a new generation when the limit is exceeded.)


Convergence Curve (for single-objective):

```
import matplotlib.pyplot as plt
import numpy as np

from pymoo.algorithms.so_genetic_algorithm import GA
from pymoo.factory import get_problem
from pymoo.optimize import minimize

problem = get_problem("sphere", n_var=10)

res = minimize(problem,
               GA(pop_size=20, eliminate_duplicates=True),
               ("n_evals", 1000),
               seed=1,
               save_history=True,
               verbose=False)

n_evals = np.array([algorithm.evaluator.n_eval for algorithm in res.history])
F = np.array([algorithm.opt[0].F[0] for algorithm in res.history])
plt.plot(n_evals, F, '--', color="black", label="GA - pop_size=20")

res = minimize(problem,
               GA(pop_size=50, eliminate_duplicates=True),
               ("n_evals", 1000),
               seed=1,
               save_history=True,
               verbose=False)

n_evals = np.array([algorithm.evaluator.n_eval for algorithm in res.history])
F = np.array([algorithm.opt[0].F[0] for algorithm in res.history])
plt.plot(n_evals, F, '--', color="green", label="GA - pop_size=50")

plt.title("Convergence")
plt.legend()
plt.xlabel("n_evals")
plt.ylabel("F")
plt.yscale("log")
plt.show()

```

**Comment by Peng-YM** [comment]
Thank you very much!
