### ISSUE TITLE
upper and lower bound constraints are not being checked

### ISSUE THREAD

**Issue by dbmptr** [msu-coinlab/pymoo#57]
Consider the OSY problem:
http://pymoo.org/problems/multi/osy.html

> from pymoo.factory import get_problem
problem = get_problem("osy")

There are 6 variables, each having upper and lower bound constraints. There are some additional inequality constraints as well. So there could be two types of infeasibilities resulting from

- violation of inequality constraints,
- violation of upper and lower bound constraints.

However, the `problem.evaluate` method detects only first type of infeasibility and not the second type. 

For example, let's take 
> x = np.array([5, 1, 1, -0.5, 1, 0])

Clearly, the x4 (i.e. `x[3]`) variable's boundary constraints are violated, as it should lie between 0 and 6, while it is set at -0.5. 
Now let's evaluate this `x` and check its feasibility.

> F, CV, feasible = problem.evaluate(x, return_values_of=["F", "CV", "feasible"])

Surprisingly, the return value of `feasible` is `true`, whereas it should have been `false`.

Why are the upper and lower bound constraints are not being treated simply as another set of inequality constraints?

**Comment by julesy89** [comment]
Thanks for your feedback. That is in fact a very good question and we have thought about this issue while creating the `Problem` architecture. 

Most algorithms in `pymoo` need to have lower and upper bounds, `xl` and `xu` provided. The algorithms are constructed to only search in the box constraints and it is made sure that these constraints are satisfied at anytime. In general, many algorithms proposed in the literature do **NOT** consider constraints in general, but handle box constraints. 

However, additional constraints are defined by `n_constr` as you might have seen and are handled by using the parameter-less approach in most algorithms. 

I agree if you design your own algorithm this might be necessary. I have added an option to the problem to consider the bounds.

```
problem = OSY()
problem.bounds_as_constraints = True

x = np.array([5, 1, 1, -0.5, 1, 0])
F, CV, feasible = problem.evaluate(x, return_values_of=["F", "CV", "feasible"])

print(F, CV, feasible)
```

Please also note this increases the number of constraints by two times the number of variables.
Can you please install the current master branch (`git clone` and then `pip install .`) to see if this works for you?

**Comment by julesy89** [comment]
Thanks for your feedback. That is in fact a very good question and we have thought about this issue while creating the `Problem` architecture. 

Most algorithms in `pymoo` need to have lower and upper bounds, `xl` and `xu` provided. The algorithms are constructed to only search in the box constraints and it is made sure that these constraints are satisfied at anytime. In general, many algorithms proposed in the literature do **NOT** consider constraints in general, but handle box constraints. 

However, additional constraints are defined by `n_constr` as you might have seen and are handled by using the parameter-less approach in most algorithms. 

I agree if you design your own algorithm this might be necessary. I have added an option to the problem to consider the bounds.

```
problem = OSY()
problem.bounds_as_constraints = True

x = np.array([5, 1, 1, -0.5, 1, 0])
F, CV, feasible = problem.evaluate(x, return_values_of=["F", "CV", "feasible"])

print(F, CV, feasible)
```

Please also note this increases the number of constraints by two times the number of variables.
Can you please install the current master branch (`git clone` and then `pip install .`) to see if this works for you?

**Comment by dbmptr** [comment]
Thanks Julian.

I checked that it is showing infeasible now.
 
But still there is an inconsistency between the bound constraints and the inequality constraints. 
For example:
```
problem = OSY()
problem.set_boundaries_as_constraints(True)

x = np.array([5, 1, 1, -0.5, 1, 0])
F, G, dG, feasible = problem.evaluate(x, return_values_of=["F", "G", "dG", "feasible"])

print(feasible)    # correctly outputs false now
print(problem.n_constr)    # correctly outputs 18 constraints
print(G.shape)      # correctly outputs (18,)
print(dG.shape)     # Still shows (6, 6) instead of (18, 6)
```
Shouldn't the number of constraints be same as the number of constraint-gradients?

**Comment by julesy89** [comment]
Yes good catch. I feel at some point the `Problem` class needs to be reengineered because it became pretty convoluted. I have quickly derived the gradients for the boundary constraints. Please quickly validated if they are correct. The latest commit contains the changes.

Please note that `dCV` is not available through the function evaluation but can be easily derived from `G` and `dG`.

**Comment by dbmptr** [comment]
Thanks,

I checked that it works. 

When the design space is high dimensional, and only few variables have bounds, then this solution may be inefficient, as it creates an entry for every variable. 
But I think, for now, adding constraints and gradients for the variables on an individual level might be difficult. If that is the case, then you may close this issue. 
However, you could consider this while reengineering the `Problem` class in future.

Anyways, thanks for your quick response.
