### ISSUE TITLE
Plot in separate windows

### ISSUE THREAD

**Issue by shdotcom** [msu-coinlab/pymoo#6]
Hi,

Is it possible to make the graph plotted in separate windows instead of inline plot.
Regarding to RNSGA3 is it developped based on this paper: 
> Reference point based multi-objective optimization using evolutionary algorithms. 

Thank you

**Comment by julesy89** [comment]
For plotting tutorial please have a look at https://matplotlib.org/examples/pylab_examples/multiple_figs_demo.html or other plotting libraries of your choice. 

R-NSGAIII is based on: 
"Reference Point Based NSGA-III for Preferred Solutions" by Yash Vesikar, Kalyanmoy Deb, Julian Blank. We published it recently at the IEEE-SSCI 2018 conference and it should be available soon. It scales up for higher dimensions and provides uniform distributed solutions near to references point.

**Comment by shdotcom** [comment]
Thank you
