### ISSUE TITLE
Problem fails to save history during minimize using Dask parallelization

### ISSUE THREAD

**Issue by jstammers** [msu-coinlab/pymoo#62]
Hi,
I am unable to solve an optimization problem when using Dask to parallelize it if `save_history` is set to `true`.

The error seems to occur when calling `copy.deepcopy` on the `Problem` object, because it can't serialize the `client` object that gets assigned to `problem.parallelization`

The following example should reproduce the bug
```python
from dask.distributed import Client
import numpy as np
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.model.problem import Problem
from pymoo.optimize import minimize

def fun(x):
    return {
        "F": np.sum(x ** 2)
    }

class MyProblem(Problem):

    def __init__(self, *args, **kwargs):
        super().__init__(n_var=10, n_obj=1, n_constr=0, xl=-5, xu=5,
                         elementwise_evaluation=True, *args, **kwargs)

if __name__=='__main__':
    client = Client()
    problem = MyProblem(parallelization=("dask", client, fun))
    X = np.random.random((10, problem.n_var))
    algorithm = NSGA2(pop_size=10, eliminate_duplicates=True)

    res = minimize(problem,
                   algorithm,
                   seed=1,
                   pf=problem.pareto_front(use_cache=False),
                   save_history=True,
                   verbose=True)
```

**Comment by julesy89** [comment]
Thanks for letting me know. If `save_history` is enabled the algorithm object can grow pretty quickly. 

For a more selective recording purpose you can also provide a callback objective which stores only the data you need later to have a look at.

I have now added to the `Problem` class that the parallelization object is never serialized. 

```
    def __getstate__(self):
        state = self.__dict__.copy()
        # never pickle the parallelization object - it always causes issue or might not be possible at all
        state["parallelization"] = None
        return state

```

Please check out the current master branch and see if this works for you now.
