### ISSUE TITLE
MOEAD: Number of solutions reduced to 1, second generation onwards 

### ISSUE THREAD

**Issue by astha736** [msu-coinlab/pymoo#65]
Hi, 

While trying to run use MOEAD algorithm for optimization, I am facing the  following issue:
- The number of solutions that are evaluated after first generation reduces to 1. 

The issue can be recreated using the following sample script: 

```
import numpy as np
from pymoo.util.misc import stack
from pymoo.model.problem import Problem

from pymoo.algorithms.moead import MOEAD
from pymoo.factory import get_problem, get_visualization, get_reference_directions
from pymoo.optimize import minimize

class MyProblem(Problem):

    def __init__(self):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=0,
                         xl=np.array([-2,-2]),
                         xu=np.array([2,2]))

    def _evaluate(self, x, out, *args, **kwargs):
        print("[DEBUG] No of solutions to evaluate per generation: {}".format(len(x)))
        f1 = x[:,0]**2 + x[:,1]**2
        f2 = (x[:,0]-1)**2 + x[:,1]**2

        out["F"] = np.column_stack([f1, f2])


problem = MyProblem()

algorithm = MOEAD(
    get_reference_directions("das-dennis", 2, n_partitions=12),
    n_neighbors=15,
    decomposition="pbi",
    prob_neighbor_mating=0.7,
    seed=1
)

res = minimize(
    problem,
    algorithm,
    ('n_gen', 20),
)

get_visualization("scatter").add(res.F).show()
```

Below is the output: 

```
Setting number of neighbours to population size: 13
[DEBUG] No of solutions to evaluate per generation: 13
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
[DEBUG] No of solutions to evaluate per generation: 1
```

Pymoo Version: 0.4.1

Please kindly guide me through this. 

Regards,
Astha

**Comment by julesy89** [comment]
Yes this is how the algorithm was proposed. I have used the original C code as a basis for my implementation. 

Interestingly, I wanted to parallelize the *for* loop to have the whole population size evaluated at once. If you do that the performance of the algorithm drops **significantly**. If you read the paper you will also see the *for* loop  (one individual at a time) is the correct way. 
However, the number of generations is only increased after the iteration over all indices.

**Comment by astha736** [comment]
Hi, 

Thank you for the explanation. Since in my problem, the time taken to evaluate an individual is significantly large, evaluating one solution at a time isn't feasible. 

I have another question regarding constraint handling, I will open a new issue for it. 

Thank you for guiding me.

Regards,
Astha
