### ISSUE TITLE
[Bug] Class method and instance method has the same name

### ISSUE THREAD

**Issue by Peng-YM** [msu-coinlab/pymoo#71]
In `pymoo.model.population`, the class `Population` has two functions sharing the same name `merge`.**In Python, Class methods and instance methods live in the same namespace, therefore, the latter one will overwrite the former one**. My suggestion is to remove the instance method. And let the `merge` method supports merge multiple populations and multiple individuals.

https://github.com/msu-coinlab/pymoo/blob/4e80b44e8f81dde0f9239656ff16189fb9a5eb68/pymoo/model/population.py#L17-L29

**Comment by julesy89** [comment]
Yeah good catch. I have first used the instance method but then realized it should have been a class method.
