### ISSUE TITLE
How to apply crossover to two individuals?

### ISSUE THREAD

**Issue by Peng-YM** [msu-coinlab/pymoo#72]
Hi Julian, I want to implement an (u+1) algorithm on pymoo. However, I don't know how to apply crossover to only two individuals. The crossover interface seems difficult to achieve this goal. Could you please help me resolve this issue? Great thanks for your help!

**Comment by julesy89** [comment]
It is actually quite straightforward. You provide a population of size two and set the parents to the first and second individual.

```
import numpy as np

from pymoo.operators.crossover.simulated_binary_crossover import SimulatedBinaryCrossover
from pymoo.operators.sampling.random_sampling import FloatRandomSampling
from pymoo.problems.single import Rastrigin

problem = Rastrigin(n_var=30)
pop = FloatRandomSampling().do(problem, 2)

parents = np.array([[0, 1]])

off = SimulatedBinaryCrossover(eta=20).do(problem, pop, parents)

print(off)
```

if you implement a 1+1 can you do a pull request? Thought about it for a while but did not find the time yet for it.

**Comment by Peng-YM** [comment]
Hi, Julian. I spent some time adding the functionality of the 1+1 crossover. I introduced the `multimethod` package to achieve this. The core implementation is as follows:
```python
class Crossover:
    def do(self, problem, a, b, **kwargs):
        @overload
        def cross(a: isa(Individual), b: isa(Individual)):
            pop = Population.create(a, b)
            parents = np.array([[0, 1]])
            return cross(pop, parents)

        @overload
        def cross(pop: isa(Population), parents: isa(np.ndarray)):
            # the original impelmentation
            pass
        return cross(a, b)
```
The `overload` decorator will dispatch to different `cross` functions according to the argument type automatically.

I think function overloading (or multiple dispatches) can be very useful for `pymoo`. For example, currently, in the `Repair` class, the `do` instance method can only accept a population as input.
```
class Repair:
    def do(self, problem, pop, **kwargs):
        return self._do(problem, pop, **kwargs)
```
However, sometimes we need to repair a single solution. We have to construct a population contains only one solution. This issue can also be solved using function overloading instead of using manual type checking everywhere.

**Comment by Peng-YM** [comment]
If you think this modification is appropriate, I will open a PR as soon as possible:).

**Comment by julesy89** [comment]
Yes looks good to me! Because in pymoo most algorithms are based on a population this not really necessary to have. But for 1+1 and others it makes the implementation easier.
Great!
