### ISSUE TITLE
Feature request: Only save data that is necessary to return the history

### ISSUE THREAD

**Issue by renatobellotti** [msu-coinlab/pymoo#75]
I am facing problems when I try to structure my code properly. To evaluate an individual, I need a `tf.keras` model. From an OOP perspective, it would be nice if I could set it in the constructor of my problem class. However, I lose the ability to save the history if I do this. The error message says:

``TypeError: can't pickle _thread._local objects``

The only way to circumvent the problem seems to be to make the surrogate model a global variable. Unfortunately, that means I cannot split my source files properly and have to do everything in the same file.

From what I read in issue #62 , saving has already been a problem for other people.

Is it possible to save only the objectives and constraints for each generation, along with the non-dominated set, instead of the entire object? Or even better, is it possible to save only the needed variables? Then you could let the user decide which of his/her variables should be saved by overriding a callback function.

**Comment by renatobellotti** [comment]
Update:

I was able to solve the problem by overriding the `__getstate__()` function of my `Problem` class:

```python
state = super().__getstate__().copy()
        del state['_surr']
        return state
```

Sorry for the inconvenience. I hope this might help somebody who is facing a similar problem in the future.

**Comment by julesy89** [comment]
That is one option. You can also use the `Callback` object as shown here: 
https://pymoo.org/interface/callback.html

and only store the necessary information you need later on.
