### ISSUE TITLE
Pareto front files are not copied when package is installed

### ISSUE THREAD

**Issue by cyrilpic** [msu-coinlab/pymoo#77]
When installing pymoo (through `pip install pymoo` or `python setup.py install`), the Pareto front files in `pymoo/problems/pf` are not copied over and are then not available.

In order to reproduce the problem, you can run this in a clean docker image:

```
$ docker run -it --rm python:3.7 bash
$ pip install pymoo
```

Then in a python console:
```python
from pymoo.factory import get_problem
p = get_problem("osy")
p.pareto_front()
```

This will return None.

**Comment by julesy89** [comment]
I have added the Pareto-front to the latest release. Can you please check if that works for you now?

All the pf files increase the release quite a bit. Probably it would be better to keep an option to download the pf files from a remote server if desired.

**Comment by cyrilpic** [comment]
Yes, it works now ; the Pareto fronts get installed with the package.

And yes, ideally, there would be a way to fetch them, for example from GitHub.

**Comment by julesy89** [comment]
Thanks for checking it out so quickly!
