### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by lureevnat** [msu-coinlab/pymoo#8]
```
problem = MyProblem(dataset)
ref_dirs = UniformReferenceDirectionFactory(3, n_points=91).do()
res = minimize(problem,
               method='nsga3',
               method_args={
                   'pop_size': 30,
                   'ref_dirs': ref_dirs},
               termination=('n_gen', 100),               
               seed=1,
               disp=True)
```
While running above code I am getting below warning. Will it effect the end results?

> 86    | 2580   
> /home/coea/anaconda3/envs/pymoo/lib/python3.6/site-packages/pymoo/algorithms/nsga3.py:221: RuntimeWarning: invalid value encountered in true_divide
>   N = (F - utopian_point) / (nadir_point - utopian_point)
> 87    | 2610

**Comment by julesy89** [comment]
sorry for my late answer. You can ignore this warning right now but I will fix it soon. I guess your problem has constraints?

**Comment by lureevnat** [comment]
Ok Julesy. Thanks.
