### ISSUE TITLE
Parallelization IndexError: too many indices for array

### ISSUE THREAD

**Issue by zhengzheng170512** [msu-coinlab/pymoo#84]
Hello Julian Blank, I modified the example in Getting Started into parallelization as follows(words in bold are what I added, but MarkDown does not make words at some places bold, so these words are bracketed with two stars): 

import numpy as np
from pymoo.util.misc import stack
from pymoo.model.problem import Problem

class MyProblem(Problem):

    def __init__(self, ****kwargs**):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=2,
                         xl=np.array([-2,-2]),
                         xu=np.array([2,2]),
                         **elementwise_evaluation=True**,
                         ****kwargs**)

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = x[:,0]**2 + x[:,1]**2
        f2 = (x[:,0]-1)**2 + x[:,1]**2

        g1 = 2*(x[:, 0]-0.1) * (x[:, 0]-0.9) / 0.18
        g2 = - 20*(x[:, 0]-0.4) * (x[:, 0]-0.6) / 4.8

        out["F"] = np.column_stack([f1, f2])
        out["G"] = np.column_stack([g1, g2])

    # --------------------------------------------------
    # Pareto-front - not necessary but used for plotting
    # --------------------------------------------------
    def _calc_pareto_front(self, flatten=True, **kwargs):
        f1_a = np.linspace(0.1**2, 0.4**2, 100)
        f2_a = (np.sqrt(f1_a) - 1)**2

        f1_b = np.linspace(0.6**2, 0.9**2, 100)
        f2_b = (np.sqrt(f1_b) - 1)**2

        a, b = np.column_stack([f1_a, f2_a]), np.column_stack([f1_b, f2_b])
        return stack(a, b, flatten=flatten)

    # --------------------------------------------------
    # Pareto-set - not necessary but used for plotting
    # --------------------------------------------------
    def _calc_pareto_set(self, flatten=True, **kwargs):
        x1_a = np.linspace(0.1, 0.4, 50)
        x1_b = np.linspace(0.6, 0.9, 50)
        x2 = np.zeros(50)

        a, b = np.column_stack([x1_a, x2]), np.column_stack([x1_b, x2])
        return stack(a,b, flatten=flatten)

problem = MyProblem(**parallelization = ("threads", 4)**)

from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_sampling, get_crossover, get_mutation

algorithm = NSGA2(
    pop_size=40,
    n_offsprings=10,
    sampling=get_sampling("real_random"),
    crossover=get_crossover("real_sbx", prob=0.9, eta=15),
    mutation=get_mutation("real_pm", eta=20),
    eliminate_duplicates=True
)

from pymoo.optimize import minimize

res = minimize(problem,
               algorithm,
               seed=1,
               pf=problem.pareto_front(use_cache=False),
               save_history=True,
               verbose=**False**)

However, I got an error as follows:
d:\FangCloudV2\personal_space\work\pymoo>python test.py

Compiled modules for significant speedup can not be used!
https://pymoo.org/installation.html#installation

To disable this warning:
from pymoo.configuration import Configuration
Configuration.show_compile_hint = False

Traceback (most recent call last):
  File "test.py", line 67, in <module>
    res = minimize(problem,
  File "d:\Program Files (x86)\Python38\lib\site-packages\pymoo\optimize.py", line 76, in minimize
    res = algorithm.solve()
  File "d:\Program Files (x86)\Python38\lib\site-packages\pymoo\model\algorithm.py", line 208, in solve
    self._solve(self.problem)
  File "d:\Program Files (x86)\Python38\lib\site-packages\pymoo\model\algorithm.py", line 283, in _solve
    self._initialize()
  File "d:\Program Files (x86)\Python38\lib\site-packages\pymoo\algorithms\genetic_algorithm.py", line 74, in _initialize
    self.evaluator.eval(self.problem, pop, algorithm=self)
  File "d:\Program Files (x86)\Python38\lib\site-packages\pymoo\model\evaluator.py", line 52, in eval
    self._eval(problem, pop[I], **kwargs)
  File "d:\Program Files (x86)\Python38\lib\site-packages\pymoo\model\evaluator.py", line 71, in _eval
    out = problem.evaluate(pop.get("X"),
  File "d:\Program Files (x86)\Python38\lib\site-packages\pymoo\model\problem.py", line 265, in evaluate
    out = self._evaluate_elementwise(X, calc_gradient, out, *args, **kwargs)
  File "d:\Program Files (x86)\Python38\lib\site-packages\pymoo\model\problem.py", line 382, in _evaluate_elementwise
    ret = pool.starmap(evaluate_in_parallel, params)
  File "d:\Program Files (x86)\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "d:\Program Files (x86)\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "d:\Program Files (x86)\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "d:\Program Files (x86)\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "d:\Program Files (x86)\Python38\lib\site-packages\pymoo\model\problem.py", line 484, in evaluate_in_parallel
    func(_x, _out, *args, **kwargs)
  File "test.py", line 17, in _evaluate
    f1 = x[:,0]**2 + x[:,1]**2
IndexError: too many indices for array

It seems that the example is a population based problem (as x is two-dimensional), while the function _evaluate_elementwise in problem.py treats only non-population based problems(as X is one-dimensional). I am not sure if my understanding is correct. I hope you can help me to solve this problem. Thank you.

**Comment by julesy89** [comment]
The parallelization only works if `elementwise_evaluation` is enabled.
I have already modified the getting started guide for the next release to be more clear on the different problem definitions.

The corresponding elementwise problem definition looks as follows:

```
import numpy as np
from pymoo.util.misc import stack
from pymoo.model.problem import Problem

class MyProblem(Problem):

    def __init__(self):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=2,
                         xl=np.array([-2,-2]),
                         xu=np.array([2,2]),
                         elementwise_evaluation=True)

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = x[0]**2 + x[1]**2
        f2 = (x[0]-1)**2 + x[1]**2

        g1 = 2*(x[0]-0.1) * (x[0]-0.9) / 0.18
        g2 = - 20*(x[0]-0.4) * (x[0]-0.6) / 4.8

        out["F"] = [f1, f2]
        out["G"] = [g1, g2]

```

Some more information about parallelization are provided here: https://pymoo.org/problems/parallelization.html
The multiple thread examples is what you are intending to implement.

**Comment by zhengzheng170512** [comment]
Thank you. I can run the example in parallelization now. However, the time of parallelization is longer than that without parallelization.

`import numpy as np
from pymoo.util.misc import stack
from pymoo.model.problem import Problem
from pymoo.configuration import Configuration
Configuration.show_compile_hint = False
import time

class MyProblem(Problem):

    def __init__(self, **kwargs):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=2,
                         xl=np.array([-2,-2]),
                         xu=np.array([2,2]),
                         elementwise_evaluation=True,
                         **kwargs)

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = x[0]**2 + x[1]**2
        f2 = (x[0]-1)**2 + x[1]**2

        g1 = 2*(x[0]-0.1) * (x[0]-0.9) / 0.18
        g2 = - 20*(x[0]-0.4) * (x[0]-0.6) / 4.8

        out["F"] = [f1, f2]
        out["G"] = [g1, g2]

problem = MyProblem(parallelization = ("threads", 4))

from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_sampling, get_crossover, get_mutation

algorithm = NSGA2(
    pop_size=40,
    n_offsprings=10,
    sampling=get_sampling("real_random"),
    crossover=get_crossover("real_sbx", prob=0.9, eta=15),
    mutation=get_mutation("real_pm", eta=20),
    eliminate_duplicates=True
)

from pymoo.optimize import minimize

start = time.time()
res = minimize(problem,
               algorithm,
               seed=1,
               pf=problem.pareto_front(use_cache=False),
               save_history=True,
               verbose=False)
end = time.time()
print('time:', end - start, 'seconds')

class MyProblem1(Problem):

    def __init__(self):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=2,
                         xl=np.array([-2,-2]),
                         xu=np.array([2,2]),
                         elementwise_evaluation=False)

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = x[:,0]**2 + x[:,1]**2
        f2 = (x[:,0]-1)**2 + x[:,1]**2

        g1 = 2*(x[:, 0]-0.1) * (x[:, 0]-0.9) / 0.18
        g2 = - 20*(x[:, 0]-0.4) * (x[:, 0]-0.6) / 4.8

        out["F"] = np.column_stack([f1, f2])
        out["G"] = np.column_stack([g1, g2])

problem = MyProblem1()

from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_sampling, get_crossover, get_mutation

algorithm = NSGA2(
    pop_size=40,
    n_offsprings=10,
    sampling=get_sampling("real_random"),
    crossover=get_crossover("real_sbx", prob=0.9, eta=15),
    mutation=get_mutation("real_pm", eta=20),
    eliminate_duplicates=True
)

from pymoo.optimize import minimize

start = time.time()
res = minimize(problem,
               algorithm,
               seed=1,
               pf=problem.pareto_front(use_cache=False),
               save_history=True,
               verbose=False)
end = time.time()
print('time:', end - start, 'seconds')`

d:\FangCloudV2\personal_space\work\pymoo>python test.py
time: 1.5059242248535156 seconds
time: 0.9865670204162598 seconds

The webpage: https://pymoo.org/problems/parallelization.html explains:
"Please note, that for small examples as shown here vectorization will always be faster. However, problem evaluation functions which are based on simulations can often not be easily vectorized because of their independent behavior."

Parallelization with multi-threads on one core costs more time than that without parallelization. How about parallelization with multi-threads on multi-cores(one thread one core)?

**Comment by julesy89** [comment]
Thanks  for pointing this out. The problem is that the thread pool is created in every evaluation.
However, you can always pass your own `Generic Starmap Interface` object.

`
import multiprocessing
from multiprocessing.pool import ThreadPool

import numpy as np
from pymoo.util.misc import stack
from pymoo.model.problem import Problem
from pymoo.configuration import Configuration

Configuration.show_compile_hint = False
import time


class MyProblem(Problem):

    def __init__(self, **kwargs):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=2,
                         xl=np.array([-2, -2]),
                         xu=np.array([2, 2]),
                         elementwise_evaluation=True,
                         **kwargs)

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = x[0] ** 2 + x[1] ** 2
        f2 = (x[0] - 1) ** 2 + x[1] ** 2

        g1 = 2 * (x[0] - 0.1) * (x[0] - 0.9) / 0.18
        g2 = - 20 * (x[0] - 0.4) * (x[0] - 0.6) / 4.8

        out["F"] = [f1, f2]
        out["G"] = [g1, g2]


pool = ThreadPool(8)
problem = MyProblem(parallelization=('starmap', pool.starmap))
`

which results in almost the same evaluation time.

`
time: 0.3971977233886719 seconds
time: 0.3871159553527832 seconds
`

You can also choose to provide a pool of threads or processes this way.

I should change this to be explained in more detail in the tutorial.
