### ISSUE TITLE
Is it possible to save intermediate result and resume an algorithm?

### ISSUE THREAD

**Issue by AIasd** [msu-coinlab/pymoo#86]
Hi!
I wonder if it is possible to save intermediate result and resume an algorithm?

**Comment by julesy89** [comment]
Yes you can do that. Also, you can add a callback to save results at each generation.
https://pymoo.org/interface/callback.html
The `Callback` object can store all intermediate results you need.

Also, you can use the algorithm indirectly and just call the `next` method.
(This is a bit more hacky way and I am not sure if this works for all algorithms).

```
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_problem, get_termination
from pymoo.visualization.scatter import Scatter

problem = get_problem("zdt1")

algorithm = NSGA2(pop_size=100)

termination = get_termination('n_gen', 200)

algorithm.initialize(problem, verbose=True)

algorithm._initialize()

while termination.do_continue(algorithm):
    algorithm.next()

algorithm.finalize()

plot = Scatter()
plot.add(problem.pareto_front(), plot_type="line", color="black", alpha=0.7)
plot.add(algorithm.pop.get("F"), color="red")
plot.show()
```

**Comment by AIasd** [comment]
Thanks! This is very helpful!
