### ISSUE TITLE
Hot to use (plotfit) in NEURAL NETWORK MATLAB TOOLBOX

### ISSUE THREAD

**Issue by osvaldoaesthetic** [msu-coinlab/pymoo#87]
I want to plot the predicted values form the trained NN vs the input data.
but y dont undestand the help in matlab to use **plotfit(targets1,inputs1,'name1',...)**

I have an input 3x17 matrix (x) and  a output 3x17 matrix (t).

`x = [50 37 37 37 24 51 24 37 51 24 51 15 24 37 60 37 37;  36 45 60 30 54 54 54 45 54 36 36 45 36 45 45 45 45;51 15 37 37 24 24 51 37 51 51 24 37 24 60 37 37 37];`
`t = [1034 1027 1022 1036 1021 1024 1022 1029 1025 1031 1034 1018 1031 1029 1030 1029 1029; 782 775 770 784 770 773 770 777 773 778 781 767 779 777 777 777 777; 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17]`

`net = feedforwardnet(6);`
`net = train(net,x,t);`
`y = net(x);`

And then I tried the next, but it does not work.

`plotfit(t(1,:),x(1,:),'name1',t(2,:),x(2,:),'name2',t(3,:),x(3,:),'name3')`

 any other suggertion please

**Comment by julesy89** [comment]
You have probably posted your question in the wrong project.
This is not related to pymoo.
