### ISSUE TITLE
TimeBasedTermination does not take into account of time taken for the first generation

### ISSUE THREAD

**Issue by AIasd** [msu-coinlab/pymoo#90]
In the `algorithm.py`,
```
def _solve(self, problem):

        # now the termination criterion should be set
        if self.termination is None:
            raise Exception("No termination criterion defined and algorithm has no default termination implemented!")

        # initialize the first population and evaluate it
        self._initialize()
        self._set_optimum()
        self._each_iteration()

        # while termination criterion not fulfilled
        while self.termination.do_continue(self):
            self.next()
```
`self.termination.do_continue` is only called after first generation.

In `max_time.py`,
self.start is initialized after the first time calling of `do_continue`.

To fix this problem, i think self.start should be initialized in `__init__` of `class TimeBasedTermination`.

**Comment by julesy89** [comment]
Thank you for pointing this out. I am not sure yet what the best solution would be. 

The time termination needs to be compliant with the other termination objects and they do have a common interface.
Either the time should be set when initialized, but then it might start too early.
Or the algorithm object calls an `initialize` function (during solve) which will be for all other terminations empty, but for time actually start the time.

Any suggestions what would be the *cleanest* way of implementing it?

**Comment by julesy89** [comment]
Should be fixed in the new release. Please check and let me know!
