### ISSUE TITLE
Saving additional calculation data when using multiprocessing

### ISSUE THREAD

**Issue by damoclessb** [msu-coinlab/pymoo#93]
Hey,

I came accross a problem I'm not able to resolve. I do have a rather expensive calculation to do and I do not only want to save the two objectives which are used for minimization in `out["F"]` (say `y.f1` and `y.f2` ) but I also want to keep track of the according `y.f3`  and so forth. 
Here is a symobilc example of the problem definition with a hypothethical function `func(x)`:

```
class MyProblem(Problem):

    def __init__(self):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=0,
                         xl=np.array([-2,-2]),
                         xu=np.array([2,2]))

    def _evaluate(self, x, out, *args, **kwargs):
        y = func(x)

        out["F"] = np.column_stack([y.f1, y.f2])
```

How can I save `y.f3` as well, esp. when using `parallelization = ('starmap', pool.starmap')?

Thanks for any help in advance,
Stefan

**Comment by julesy89** [comment]
Yes, what you are intending, is rather simple in pymoo. Simply set the attribute to the `out` dictionary. It will then stick to the `Individual` object throughout the whole algorithm run. 
Finally, the `opt` object (which is the same what `res.X`, `res.F`, and so on are) has all the attributes you have set.

See the following example code below:

```
import numpy as np

from pymoo.algorithms.so_genetic_algorithm import GA
from pymoo.model.problem import Problem
from pymoo.optimize import minimize


class Sphere(Problem):

    def __init__(self, n_var=2):
        super().__init__(n_var=n_var, n_obj=1, n_constr=0, xl=0, xu=1, type_var=np.double)

    def _evaluate(self, x, out, *args, **kwargs):
        out["F"] = np.sum(np.square(x - 0.5), axis=1)
        out["attr"] = x / 2


problem = Sphere()

algorithm = GA(
    pop_size=100,
    eliminate_duplicates=True)

res = minimize(problem,
               algorithm,
               termination=('n_gen', 20),
               seed=1,
               verbose=True)


print("Attribute of opt", res.opt.get("attr"))

```

**Comment by damoclessb** [comment]
Hey Julian,

thanks for the fast reply. This was definitely easier than I thought and also works when using multiprocessing. 
I'll close this issue.

Regards,
Stefan

**Comment by Seabass2015** [comment]
Hi there! 
Simply writing
out["attr"]
as an additional output/evaluation is very handy. 

However, I´ve found, that one can only assign a list or array of scalar-valued outputs to out["attr"]. 

Is it somehow possible for me to assign a list/array of OBJECTS to out["attr"] as well ? 

Thank you very much for your help!

Regards,
Seabass
