### ISSUE TITLE
ImportError: DLL load failed while importing non_dominated_sorting: The specified module could not be found.

### ISSUE THREAD

**Issue by ayubrucelan** [msu-coinlab/pymoo#99]
Hi there,

I'm new for python and pymoo and learning both of them right now.

As I tried running the example code from the pymoo document, the error as the title came out and I'm wondering someone can show me the way to fix it.

I'm using the Python 3.8, pymoo 0.4.2, and the newest Pycharm as Pycharm 2020.2.1 x64.

thank you very much.

**Comment by julesy89** [comment]
Thank you for letting me know. I have gotten another Email regarding this issue but was not able to reproduce the error.
Can you please check if it works for you with Python 3.7?

Thanks in advance,
Julian

**Comment by ayubrucelan** [comment]
I tried with Python 3.7.9 just now and the same error came out again.

**Comment by julesy89** [comment]
I have recompiled the pymoo package for Windows and Python 3.7.

Can you please check if this release works on your machine?

`pip install http://pymoo.org/pymoo-0.4.2-cp37-cp37m-win_amd64.whl`

Thanks

**Comment by ayubrucelan** [comment]
Thank you for such quick response!

I installed the version you gave me and still got error.

The error detail is shown as attachment, in which the Chinese character means "The specified module could not be found.".

I hope this is helpful for locating the problem.

![image](https://user-images.githubusercontent.com/52695846/93937446-c7448400-fd62-11ea-8404-617d1151c60e.png)

**Comment by julesy89** [comment]
Okay, so the release seems not to be the issue.
Can you try to fix it as discussed in this thread on stackoverflow?

https://stackoverflow.com/questions/44537131/numpy-library-importerror-dll-load-failed-the-specified-procedure-could-not-be

They are saying it might be an anaconda path issue. Maybe reinstall anaconda and make sure the `Add to Path` checkbox is set.

Does NumPy work for you without any issues?

**Comment by ayubrucelan** [comment]
Numpy works well so far on both Python 37&38 on my machine.

I'll check the stackoverflow later and inform you when I finished. It's 6:30 in the morning here and I really need to go to bed lol.

Thank you for your help and please wait for the further message.

**Comment by julesy89** [comment]
Thank you!
Please let me know if this resolves the issue. Also, if there would be a way for me to reproduce the error (on my Windows test system it works flawlessly).

Can you please also check to execute the following before you start: 

```
from pymoo.util.function_loader import FunctionLoader

FunctionLoader().get_instance().is_compiled = False
```

This is a hack to only use the Python and not the compiled version. I am curious if this works for you.

**Comment by ayubrucelan** [comment]
Sorry for replying late.

I've tried the code that bypasses the complied version you give me, it works perfectly on both Python 37&38.

Maybe this problem is taken place from the Pycharm side?

Anyway, thank you for your help and I'll close this issue from now.

**Comment by julesy89** [comment]
I think I have found the issue and rebuild a new version (0.4.2.1).

Can you please check if the DLL issue is gone?

To update to the newest version simply execute:

```
pip install -U --no-cache-dir pymoo
```

**Comment by ayubrucelan** [comment]
I tested in on my machine, the new version works well on Pycharm!

Thank you a lot for your tireless efforts to solve this problem!

**Comment by julesy89** [comment]
Great! No problem. I am glad it works now!
